### ISSUE TITLE
Automatic key expiration

### ISSUE THREAD

**Issue by akki166786** [brix/crypto-js#10]
I am having a scenario where i want to secure the JSON data which i am sending and storing at the client side, and i also want that, that data should be protected, The way to protect this data i suppose is encryption of the data but because the decryption logic and key is also at the client side (to decrypt the encrypted JSON data).

So to protect it i was wondering if we can set something like expiration time of key,

The way i was thinking this is to work that if someone is encrypting the data with the key then encrypted data must have some intelligence that after a period of time this data cannot be decrypted with the key with which it was encrypted(or may be cannot be decrypted at all).

is it possible? i suppose yes , and i don't it is there in the library now.

so i am asking to all members to please provide this facility in this library, or if it is not possible(which i suppose is not) or is not gonna solve a problem please justify.

Thanks.

**Comment by evanvosberg** [comment]
crypto-js is a library to provide crypto standard implementations. You can use it to build what ever you want but I won't implement such non-standard stuff here.

I think the biggest problem of your idea is to validate the time. How to check the time of the environment isn't manipulated?
