### ISSUE TITLE
SHA3 is NOT SHA3 is KECCAK!!!

### ISSUE THREAD

**Issue by jarenal** [brix/crypto-js#100]
Today I've lose the whole day trying to understand why the function SHA3 from your library and PHP doesn't match. We can avoid easily that other developers in the future waste their time in the same issue. 

**You should rename the function from SHA3 to KECCAK and add a NOTICE in the README file ASAP for avoid confusions. If you have not read this article, you should do it.** 

https://medium.com/@ConsenSys/are-you-really-using-sha-3-or-old-code-c5df31ad2b0

Thanks in advance.

**Comment by ognus** [comment]
@jarenal thanks a lot for clarification, thanks to you I wasted "only" an hour, not the whole day :) Peace!

**Comment by jarenal** [comment]
@ognus You are welcome! At least it helped someone 😄

**Comment by evanvosberg** [comment]
keep only one issue open related to this https://github.com/brix/crypto-js/issues/173
