### ISSUE TITLE
problem of decrypt (AES, Rabbit and other)

### ISSUE THREAD

**Issue by habi4ek** [brix/crypto-js#11]
var secret = CryptoJS.ASE.encrypt('user','secret'); // U2FsdGVkX19oU61BktfTADc18gnyiSOCV8DX+F5Plf8=
var ulog = CryptoJS.RC4.decrypt(secret,'secret'); // 75736572

decoding  on all algorithms returns 75736572

**Comment by ghost** [comment]
User encoder for .toString() method:

```
var secret = CryptoJS.AES.encrypt('user', 'secret').toString(CryptoJS.enc.HEX); 
// U2FsdGVkX19WHCNvCvh/9w4oe/EVjkwsepDJ78nz+gw=

var plain = CryptoJS.AES.decrypt(secret, 'secret').toString(CryptoJS.enc.Latin1);
// user
```

**Comment by habi4ek** [comment]
Thank you very much
