### ISSUE TITLE
Support for aes GCM mode

### ISSUE THREAD

**Issue by graingert** [brix/crypto-js#136]

**Comment by oshoghi** [comment]
CBC is known to have vulnerabilities.  Any plans to support GCM?

**Comment by graingert** [comment]
CBC isn't actually more vulnerable than GCM. It's got some interesting foot
guns regarding padding and MAC/encrypt order. The real advantage of GCM is
that it can be computed in parallel

**Comment by oshoghi** [comment]
@graingert CBC has a known vulnerability outlined here: ~https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-38d.pdf~ (sorry, wrong link: https://blog.cloudflare.com/padding-oracles-and-the-decline-of-cbc-mode-ciphersuites/) . What makes you say GCM is no less secure?

**Comment by lixmal** [comment]
> @graingert CBC has a known vulnerability outlined here: ~https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-38d.pdf~ (sorry, wrong link: https://blog.cloudflare.com/padding-oracles-and-the-decline-of-cbc-mode-ciphersuites/) . What makes you say GCM is no less secure?

The vulnerability is relevant to TLS (<1.3), not CBC in general.
It's a MAC/Encryption order problem as mentioned in the article and by @graingert.
It will never get fixed, instead CBC ciphers were removed from TLS1.3.

Another advantage of GCM would be that there's only one key required instead of two (one for MAC, one for CBC).

**Comment by jyxjjj** [comment]
Never Say Good Or Not.
If your boss asked, will you response as 'It's secure enough'?
This is a feature request and the decision is yours.
If i know how to do this i will submit codes as pull request instead of talk if CBC is more secure or not.
(May be this words have a bad attitude, but it's not that means,  I am only talk the fact.)

**Comment by AirBorne04** [comment]
Due to compatibility i need aes-gcm encryption can we get it into the lib?

**Comment by lucasbiel7** [comment]
I'm looking for AES-GCM feature

**Comment by ashok-kumar** [comment]
+1

**Comment by val-o** [comment]
Is there any userland crypto-js compatible implementation?

**Comment by CheariX** [comment]
`AES-CBC` is well-known for its malleability vulnerability. [TLS was just one (of many) examples where this could go wrong](https://scholar.google.de/scholar?q=AES+CBC+malleability). In general, we do need _authenticated_ encryption (AE), for example, AES GCM.
Does `crypto-js` support any kind of AE?

**Comment by jyxjjj** [comment]
> `AES-CBC` is well-known for its malleability vulnerability. [TLS was just one (of many) examples where this could go wrong](https://scholar.google.de/scholar?q=AES+CBC+malleability). In general, we do need _authenticated_ encryption (AE), for example, AES GCM.
> Does `crypto-js` support any kind of AE?

You should not use TLS as an example. Google used TLS 1.2\~1.3, X25519/secp384r1 and AES-128\~256-GCM. So TLS is not only support non-AEAD-AES.

My reply was been deleted with this issue page.
And such a long times later, there's no good news as a response from this repo's team.
So i think they are non-friendly.

I wanted to make something client by NW.js and server by PHP, so i learnt this repo.
But now i am calling OpenSSL EVP DLLs to do AES-GCM or other encryptions.
With NodeJS "node-ffi".

**Comment by armin-mimosa** [comment]
+1 bump

**Comment by graingert** [comment]
> +1 bump

Hey thanks for the bump. I no longer use crypto-js

**Comment by travis-infosec** [comment]
I'm a praticing cryptographer, and I still think this is a good idea.  We generally don't use CBC any more because of the malleability, and GCM is fine for most purposes, and quite fast.  Yes, we could do encrypt-then-MAC as @graingert implies, but then we'd lose the speed of the simple checksum polynomial, AND we'd have to do two passes over the data.  GCM is the new CBC.

**Comment by hpelitebook745G2** [comment]
@graingert what do you use now?
Previously my backend in Java is using: `Cipher.getInstance("AES/CBC/NoPadding");` and both Frontend and Backend work already. However, Fortify code scan is suggesting `GCM` padding for security.
Now, backend Java is using: `Cipher.getInstance("AES/GCM/PKCS5Padding","BC");` so I'm wondering how to translate this using `crypto-js`.

Appreciate your advice.

**Comment by graingert** [comment]
AES GCM is supported directly in the web API:
https://developer.mozilla.org/en-US/docs/Web/API/AesGcmParams

**Comment by Neneil94** [comment]
I wanted to use this library in my expo react native project until I found out GCM is not supported. Currently I am working with sjcl library but I get some weird errors like `gcm: tag doesn't match`. 

I have encrypted some stuff with web API with AES-GCM and now I want to decrypt this in my expo react native app. I can't find a suitable library :( Any suggestions?

**Comment by junaiddarajat** [comment]
@Neneil94 I'm on the same boat, what did you end up doing?

**Comment by Neneil94** [comment]
@junaiddarajat I am using [sjcl](https://github.com/bitwiseshiftleft/sjcl) now and I am happy with that. It is important to use the correct encodings.
Maybe this code example will help you:
```
// convert into sjcl needed formats
let bkey = sjcl.codec.base64.toBits(aesKey);
let cipher = new sjcl.cipher.aes(bkey);
let bdata = sjcl.codec.base64.toBits(data);
let biv = sjcl.codec.base64.toBits(iv);

// decrypt
let decbits = sjcl.mode.gcm.decrypt(cipher, bdata, biv);

// convert into utf8string
decryptedData = sjcl.codec.utf8String.fromBits(decbits);
```
You MUST adapt it into your encoding structure. It is possible that you use other formats e.g. for aesKey, data and iv.

**Comment by junaiddarajat** [comment]
@Neneil94 cheers! I'm still stuck though and got the same error as yours, so if you could maybe look at my comment at the mentioned issue by trasherdk, but in any case, thanks, it's much appreciated!

**Comment by SuperRay3** [comment]
> @Neneil94 cheers! I'm still stuck though and got the same error as yours, so if you could maybe look at my comment at the mentioned issue by trasherdk, but in any case, thanks, it's much appreciated!

Hi, I found a tiny AES Crypto lib with GCM mode, hope that can help you.

**Comment by SuperRay3** [comment]
@junaiddarajat Hi, I found a tiny AES Crypto lib with GCM mode, hope that can help you.

**Comment by rhtrathod** [comment]
Can you please share link for AES GCM support

**Comment by SuperRay3** [comment]
@rhtrathod sorry for that, I forget it😂. Here it is [kingller/pandora-aes](https://github.com/kingller/pandora-aes)

**Comment by Neustradamus** [comment]
Dear all: I have done an important announcement here:
- https://github.com/brix/crypto-js/issues/536

The solution is to replace by crypto-es:
- https://github.com/entronad/crypto-es
- https://github.com/entronad/crypto-es/tags
- https://github.com/entronad/crypto-es/releases
