### ISSUE TITLE
SHA-3 outdated algorithm.

### ISSUE THREAD

**Issue by kleeb** [brix/crypto-js#139]
The most common release is using outdated SHA-3 algorithm.

More info here https://medium.com/@ConsenSys/are-you-really-using-sha-3-or-old-code-c5df31ad2b0
  

Or at least we should call it keccak-sha-3, not sha-3
This will only bring problems and confusion when syncing with other SHA-3 libs

**Comment by kangert** [comment]
This is really annoying. This should be fixed ASAP. The current code should be renamed to "**keccak**" (no sha-3 mention) and correct sha-3 should be implemented. 

Does someone has a corrected version?

**Comment by evanvosberg** [comment]
keep only one issue open related to this https://github.com/brix/crypto-js/issues/173
