### ISSUE TITLE
Malformed Utf-8 data error

### ISSUE THREAD

**Issue by SiZapPaaiGwat** [brix/crypto-js#14]
i have two string fields in database, both of them are encrypted by cryptojs v3.0.2 in client browser. and the code is like this:

```
CryptoJS.AES.encrypt(txt, key).toString()
```

today i got a Malformed Utf-8 data error when decrypting in browsers by cryptojs v3.0.2, one of them (named A)works fine,the other (named B) does not.

so i tried to decrypt them in node.js and browsers using crypto-js v3.1.2,  the decrypt code is like this:

```
    CryptoJS.AES.decrypt(txt, key).toString(CryptoJS.enc.Utf8)
```

the results is werid (the result from browser and node.js is the same).

> - i got an empty string when decrypt A
> - i got the same error when decrypt B

so the behavior is not the same between v3.0.2 and v3.1.2.

could you help me

**Comment by ghost** [comment]
I never used an older version and it wasn't part of this repository.

First I thought it could be a unicode / utf8 problem see: [The Unicode Problem](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Base64_encoding_and_decoding#The_.22Unicode_Problem.22), but it's not.  The implementations are well in both versions.

I added 2 new branches to the repo "svn-mirror/3.0.2" and "svn-mirror/3.1.2". This should make it easier to have a diff of those versions.

**Comment by SiZapPaaiGwat** [comment]
@evanvosberg thanks for your patient.

**Comment by suwu150** [comment]
please tell me how to solve this problem!
