### ISSUE TITLE
MD5 call error

### ISSUE THREAD

**Issue by giantss** [brix/crypto-js#142]
My steps:
1, `npm install crypto-js --save`
2,`import CryptoJS from 'crypto-js'`
3,`let  encryptText = CryptoJS.MD5(text);`
In the third department error:
![image](https://user-images.githubusercontent.com/13778798/34873561-8950abf0-f7d0-11e7-9c2c-6b08abbeb83b.png)

**Comment by matb33** [comment]
```
let encryptText = CryptoJS.MD5(text).toString();
```
