### ISSUE TITLE
List of modules

### ISSUE THREAD

**Issue by Shic1983** [brix/crypto-js#15]
Hi,

Where/how can I find a list of the modules.. ?

For example, I want crypto-js/aes but I also want WordArray... but don't know how I can include(?) / access wordarray though only including aes module.. etc?

Thanks,
Flibbr

**Comment by ghost** [comment]
WordArray is part of the `crypto-js/core` accessible with `CryptoJS.lib.WordArray` and not a single module.

But regarding to your question about a list of the available module, it's a nice idea and soon I'll add one to the readme file.
