### ISSUE TITLE
when i use CryptoJS.SHA256(str)  it retuns a object 

### ISSUE THREAD

**Issue by xmgdtc** [brix/crypto-js#157]
The api doc says it return a string
(message: string, key?: string, ...options: any[]) => string;

But when i use it  CryptoJS.SHA256(str),It return this
{ words:
   [ 1165750581,
     1028330380,
     -459297786,
     -947376156,
     -1078028390,
     -767246913,
     1573962699,
     -482922654 ],
  sigBytes: 32 }

I should use toString() then it returns as string.

**Comment by RossAddinall** [comment]
I encountered the same problem, in the examples it shows:

`var ciphertext = CryptoJS.AES.encrypt(JSON.stringify(data), 'secret key 123');`

which leads one to expect that the variable 'ciphertext' will, in fact, contain the encrypted data.  However, it appears to contain an object, something like this:

```
{ init: [Function],
     '$super':
      { init: [Function: init],
        toString: [Function: toString],
        '$super': [Object] },
     ciphertext: { words: [Array], sigBytes: 16 },
     key:
      { init: [Function],
        '$super': [Object],
        words: [Array],
        sigBytes: 32 },
     iv:
      { init: [Function],
        '$super': [Object],
        words: [Array],
        sigBytes: 16 },
     algorithm:
      { _doReset: [Function: _doReset],
        encryptBlock: [Function: encryptBlock],
        decryptBlock: [Function: decryptBlock],
        _doCryptBlock: [Function: _doCryptBlock],
        keySize: 8,
        init: [Function],
        '$super': [Object] },
     mode:
      { init: [Function],
        '$super': [Object],
        Encryptor: [Object],
        Decryptor: [Object] },
     padding: { pad: [Function: pad], unpad: [Function: unpad] },
     blockSize: 4,
     formatter: { stringify: [Function: stringify], parse: [Function: parse] },
     salt: { words: [Array], sigBytes: 8 } }
```

Doing this:
`console.log( "TEST: ", CryptoJS.AES.encrypt( "fred", "123" ) );
`
also prints the object, but doing this:
`console.log( "TEST: ", CryptoJS.AES.encrypt( "fred", "123" ).toString() );
`
prints the encrypted string.

To be fair the decrypt part of the same example does show the use of the toString method, but it is not clear that the purpose is to get the actual ciphertext.

`var bytes  = CryptoJS.AES.decrypt(ciphertext.toString(), 'secret key 123');`

Thanks to @xmgdtc for filing this issue, it saved me loads of time.

**Comment by michaeljakob** [comment]
Should 100% in the original doc/ intro howto
