### ISSUE TITLE
How java&JavaScript uses CryptoJS AES encryption and decryption

### ISSUE THREAD

**Issue by it-coder** [brix/crypto-js#165]
``` java
    private static final String KEY_ALGORITHM = "AES";
    private static final String DEFAULT_CIPHER_ALGORITHM = "AES/ECB/PKCS5Padding";
    private static final Integer LENGTH = 128;
   public static String encrypt(String content, String password) {
        try {
            Cipher cipher = Cipher.getInstance(DEFAULT_CIPHER_ALGORITHM);

            byte[] byteContent = content.getBytes("utf-8");

            cipher.init(Cipher.ENCRYPT_MODE, getSecretKey(password));

            byte[] result = cipher.doFinal(byteContent);

            return Base64.encodeBase64String(result);
        } catch (Exception ex) {
            logger.error("encrypt error", ex);
        }
        return null;
    }
    private static SecretKeySpec getSecretKey(final String password) {
        KeyGenerator kg = null;
        try {
            kg = KeyGenerator.getInstance(KEY_ALGORITHM);
            SecureRandom random = SecureRandom.getInstance("SHA1PRNG");
            random.setSeed(password.getBytes());
            kg.init(LENGTH, random);
            SecretKey secretKey = kg.generateKey();
            return new SecretKeySpec(secretKey.getEncoded(), KEY_ALGORITHM);
        } catch (Exception ex) {
            logger.error("error", ex);
        }
        return null;
    }
  public static void main(String[] args) throws Exception {
        System.out.println(AESUtil.encrypt("{\"serialNumber\":\"330503JD05000018060401001YDQBWEG\",\"status\":38}", "KYIDZQJKNCQRYEBARBKX"));
		// result : Dr9eeRgmt9H9ltP48Sw+FkzHEDN4cr5Ub1c5FJyZ8PGE2hseA/uNZsKowvmC2iJP6FuuHuPiviR5gywPDtBhNg==
  }
```

The above is the java encryption process, but the key bit 20.

If I change the key to 16 bits, the following can be correctly decrypted; but if it is 20 bits, it cannot be decrypted properly.

``` javascript
<script src="crypto-js.js"></script>
<script type="text/javascript">
   var bizContent = '{"serialNumber":"330503JD05000018060401001YDQBWEG","status":38}';
    var keyUtf8 = CryptoJS.enc.Utf8.parse('KYIDZQJKNCQRYEBARBKX');
   
    function encrypt(word, key) {
	 var ciphertext = CryptoJS.AES.encrypt(word, key, options);
	 return ciphertext.toString();
    }
    function decrypt(word, key){  
       var decrypt = CryptoJS.AES.decrypt(word, key, options);     
       return CryptoJS.enc.Utf8.stringify(decrypt).toString();  
    } 
    var encryptTxt = encrypt(bizContent, keyUtf8 );
    var decryptTxt = decrypt(encryptTxt, keyUtf8 );
</script>
```

I hope to get some help, how to deal with the 20-bit key in order to make my normal decryption, thank you very much.

**Comment by Udbhav12** [comment]
@javaxiaoxuetu - With 16 bit key, are you getting the same encrypted text in Java and Javascript ?

**Comment by it-coder** [comment]
> @javaxiaoxuetu - With 16 bit key, are you getting the same encrypted text in Java and Javascript ?

 
Not at all with 16 bit key.Finally I used the following code in java.
``` java
private static SecretKeySpec getSecretKey(final String password) {
        return new SecretKeySpec(password.getBytes(), KEY_ALGORITHM);
    }
```
This will get the same encrypted text.
thanks for your reply and sorry for the late reply.

**Comment by ruanyr** [comment]
> ```java
>     private static final String KEY_ALGORITHM = "AES";
>     private static final String DEFAULT_CIPHER_ALGORITHM = "AES/ECB/PKCS5Padding";
>     private static final Integer LENGTH = 128;
>    public static String encrypt(String content, String password) {
>         try {
>             Cipher cipher = Cipher.getInstance(DEFAULT_CIPHER_ALGORITHM);
> 
>             byte[] byteContent = content.getBytes("utf-8");
> 
>             cipher.init(Cipher.ENCRYPT_MODE, getSecretKey(password));
> 
>             byte[] result = cipher.doFinal(byteContent);
> 
>             return Base64.encodeBase64String(result);
>         } catch (Exception ex) {
>             logger.error("encrypt error", ex);
>         }
>         return null;
>     }
>     private static SecretKeySpec getSecretKey(final String password) {
>         KeyGenerator kg = null;
>         try {
>             kg = KeyGenerator.getInstance(KEY_ALGORITHM);
>             SecureRandom random = SecureRandom.getInstance("SHA1PRNG");
>             random.setSeed(password.getBytes());
>             kg.init(LENGTH, random);
>             SecretKey secretKey = kg.generateKey();
>             return new SecretKeySpec(secretKey.getEncoded(), KEY_ALGORITHM);
>         } catch (Exception ex) {
>             logger.error("error", ex);
>         }
>         return null;
>     }
>   public static void main(String[] args) throws Exception {
>         System.out.println(AESUtil.encrypt("{\"serialNumber\":\"330503JD05000018060401001YDQBWEG\",\"status\":38}", "KYIDZQJKNCQRYEBARBKX"));
> 		// result : Dr9eeRgmt9H9ltP48Sw+FkzHEDN4cr5Ub1c5FJyZ8PGE2hseA/uNZsKowvmC2iJP6FuuHuPiviR5gywPDtBhNg==
>   }
> ```
> 
> The above is the java encryption process, but the key bit 20.
> 
> If I change the key to 16 bits, the following can be correctly decrypted; but if it is 20 bits, it cannot be decrypted properly.
> 
> ```js
> <script src="crypto-js.js"></script>
> <script type="text/javascript">
>    var bizContent = '{"serialNumber":"330503JD05000018060401001YDQBWEG","status":38}';
>     var keyUtf8 = CryptoJS.enc.Utf8.parse('KYIDZQJKNCQRYEBARBKX');
>    
>     function encrypt(word, key) {
> 	 var ciphertext = CryptoJS.AES.encrypt(word, key, options);
> 	 return ciphertext.toString();
>     }
>     function decrypt(word, key){  
>        var decrypt = CryptoJS.AES.decrypt(word, key, options);     
>        return CryptoJS.enc.Utf8.stringify(decrypt).toString();  
>     } 
>     var encryptTxt = encrypt(bizContent, keyUtf8 );
>     var decryptTxt = decrypt(encryptTxt, keyUtf8 );
> </script>
> ```
> 
> I hope to get some help, how to deal with the 20-bit key in order to make my normal decryption, thank you very much.

hello, i have got the same question,  if i don not use "new SecretKeySpec(password.getBytes(), KEY_ALGORITHM);"  for instead in java, how to solved this problem with changing javascript?

**Comment by linonetwo** [comment]
https://github.com/brix/crypto-js/issues/334
