### ISSUE TITLE
MD5 mismatch??

### ISSUE THREAD

**Issue by cbarraford** [brix/crypto-js#188]
I must be doing something really dumb....

The following JS code outputs
```js
console.log("MD5 Message:", CryptoJS.MD5("Message").toString())
>> MD5 Message: 4c2a8fe7eaf24721cc7a9f0175115bd4
```

But if I do an md5 check on my mac via the cli, i get a different checksum

```bash
>> echo "Message" | md5
f5e9c7e42e4bded421e4476732087add
>> echo "Message" | openssl dgst -md5
f5e9c7e42e4bded421e4476732087add
```

What am I doing wrong? Best I can tell, the cli has the right answer, how do I get CryptoJS to give me the same answer as the cli commands shown above??

**Comment by cbarraford** [comment]
i was gettting a difference in the output because the `echo` command appends a new line at the end. Using `echo -n` skips the new line.

**Comment by BoleLee** [comment]
```bash
md5 image.png
MD5 (image.png) = b6a99ed321d0d542a8c07ee32f81d27d

(echo 0:; echo b6a99ed321d0d542a8c07ee32f81d27d) | xxd -rp -l 16 | base64
tqme0yHQ1UKowH7jL4HSfQ==
```

with cli, get the above result. However, with Crypto.MD5, get another result:

```bash
import Base64 from 'crypto-js/enc-base64'
import MD5 from 'crypto-js/md5'

console.log(MD5(file).toString())
console.log(Base64.stringify(MD5(file)))

487f7b22f68312d2c1bbc93b1aea445b
SH97IvaDEtLBu8k7GupEWw==
```

Where did I get it wrong, Why did they get the different result?
