### ISSUE TITLE
wordArray.clamp is not a function.

### ISSUE THREAD

**Issue by guoliang1206** [brix/crypto-js#189]
Hi, 

I have faced this problem when I used the base64 encode like this 
```
export function base64Encode(content) {
    return CryptoJS.enc.Base64.stringify(content);
}

```
and I have import the lib like this `import Base64 from 'crypto-js/enc-base64';`

Environment :  React-Native  0.55.4 
                       "crypto-js": "^3.1.9-1",

**Comment by guoliang1206** [comment]
sorry , the usage is complex , I FOUND THE USAGE IN SOURCE CODE

**Comment by Ackerc** [comment]
怎么解决的，我现在base64的编码有问题，看下https://github.com/brix/crypto-js/issues/190

**Comment by BoleLee** [comment]
> sorry , the usage is complex , I FOUND THE USAGE IN SOURCE CODE

How should it be use? What is the Right Parameter Type?

**Comment by BoleLee** [comment]
> > sorry , the usage is complex , I FOUND THE USAGE IN SOURCE CODE
> 
> How should it be use? What is the Right Parameter Type?

Finally I get to know what WordArray is and I use like this:
```bash
import Base64 from 'crypto-js/enc-base64'
import Utf8 from 'crypto-js/enc-utf8'

console.log(Utf8.parse('Message'))
console.log(Base64.stringify(Utf8.parse('Message')))
```

**Comment by entronad** [comment]
https://github.com/entronad/crypto-es/issues/41

**Comment by hepcat72** [comment]
I have a question... I'm using the node-red `crypto-wz` node that is a node-red interface to `crypto-js`. It encounters this error and is up to date.  Any suggestions on how to resolve this from the perspective of `crypto-wz`? Is there like a non-release version of this package that would solve it? `crypto-wz` doesn't link to a repo in npm, so I don't know where to submit an issue for them. If the current release of `crypto-js` solves this, does the call in `crypto-wz` likely need to be fixed?
