### ISSUE TITLE
Why get different result using MD5?

### ISSUE THREAD

**Issue by sirormy** [brix/crypto-js#203]
```js
const {MD5} = require('crypto-js')

// 4297f44b13955235245b2497399d7a93
const encryptedString = MD5('123123').toString();

// 487f7b22f68312d2c1bbc93b1aea445b
const encryptedNumber = MD5(123123).toString();
```

Why using 123123 is wrong? Thx

**Comment by BrodaNoel** [comment]
@Sirormy I believe it happens because it's a different binary value.

If you want to always have the same value, always parse the value to a string (or number), and that should be enough to always get the same value.
