### ISSUE TITLE
The MD5 method of Crypto get different result with cli md5

### ISSUE THREAD

**Issue by BoleLee** [brix/crypto-js#221]
## Premise
All cases use the same image.

## Description

- MacOS Mojave 10.14.4
- iTerm CLI

```bash
md5 image.png
MD5 (image.png) = b6a99ed321d0d542a8c07ee32f81d27d

(echo 0:; echo b6a99ed321d0d542a8c07ee32f81d27d) | xxd -rp -l 16 | base64
tqme0yHQ1UKowH7jL4HSfQ==
```

- lib: CryptoJS
- Wechat development Tool
- MiniProgram
- WePY
- file API: [chooseMessageFile()](https://developers.weixin.qq.com/miniprogram/dev/api/media/image/wx.chooseMessageFile.html)

```bash
import Base64 from 'crypto-js/enc-base64'
import MD5 from 'crypto-js/md5'

console.log(MD5(file).toString())
console.log(Base64.stringify(MD5(file)))

487f7b22f68312d2c1bbc93b1aea445b
SH97IvaDEtLBu8k7GupEWw==
```

```
// parameter 'file' come from: that.file
let that = this
wepy.chooseMessageFile({
        count: 1,
        type: 'image'
      }).then(function(res) {
        that.file = res.tempFiles[0]
        that.$apply()
       ...
      })
```

Where did I get it wrong, Why did they get the different result?

_Originally posted by @BoleLee in https://github.com/brix/crypto-js/issues/188#issuecomment-498503389_

**Comment by BoleLee** [comment]
I have make a little test project, which use vue-cli 3, and it may speak my puzzle clearly.
[Here is the link](https://github.com/BoleLee/cryptojs-demo)

**Comment by BoleLee** [comment]
![image](https://user-images.githubusercontent.com/11992092/58870843-86e76f80-86f3-11e9-9078-6b52aa33fc93.png)
I have no idea where has gone wrong, and was extraordinary shocked to find that different image get the same md5 value. It is happened in wechat development tool.

**Comment by BoleLee** [comment]
> ![image](https://user-images.githubusercontent.com/11992092/58870843-86e76f80-86f3-11e9-9078-6b52aa33fc93.png)
> I have no idea where has gone wrong, and was extraordinary shocked to find that different image get the same md5 value. It is happened in wechat development tool.

I have finally realized that I made a EXTRAORDINARY mistake about the file parameter which is past to CryptoJS, which is actually an Object but not a File.

In fact, wechat miniprogram has provided an API: [wx.getFileInfo](https://developers.weixin.qq.com/miniprogram/dev/api/file/wx.getFileInfo.html) to get the file digest (md5 or sha1). That is exactly what I wanted.

**Comment by BoleLee** [comment]
About wechat miniprogram upload file in activeStorage way, I have make some remark in Chinese, [here's the link](https://segmentfault.com/a/1190000019414586). Hope it will be useful for those who need it.

**Comment by JTBrinkmann** [comment]
I can't judge what your Chinese article says, but for anyone else landing here (e.g. via search results):
**The MD5 function expects a string as parameter**, calling it with anything else, including numbers & objects, you will always get `487f7b22f68312d2c1bbc93b1aea445b` for truthy values (e.g. `true`, `Math.random()`, any object). For falsey values (e.g. `undefined`, `false`, `0`) you will always get `d41d8cd98f00b204e9800998ecf8427e`. Make sure to pass a **string** to the function!
