### ISSUE TITLE
Is there any intention to migrate it from grunt to webpack?

### ISSUE THREAD

**Issue by halan** [brix/crypto-js#225]
I think that webpack is the current best option for that and way more used and maintained.

It covers all the cases Grunt does for this project currently, and it'll also make the project more approachable for new collaborators. To be honest, I tried to build the project today and I'm not able to require `build/crypto-js`, `build/index` or even `build/core`.

If there is any intention to rewrite the build using `require` and webpack I can help with that.

**Comment by halan** [comment]
I'm working in a PR: https://github.com/halan/crypto-js/tree/structuring/src

**Comment by entronad** [comment]
@halan 
It seems this repo is no longer maintained.
I am maintaining an alternative repo wich is just the same as crypto-js and written in ES6+ and with TypeScript support: [crypto-es](https://github.com/entronad/crypto-es) .
It dosen't use grunt and should be ok to imported to webpack projects.
