### ISSUE TITLE
semver change v3.1.3 to 3.2.0

### ISSUE THREAD

**Issue by jfroffice** [brix/crypto-js#23]
In the last version v3.1.3, I see that you have moved some files.

This is definitely a breaking change. You should increment the minor version number in order to respect [semver](http://semver.org/).

And probably delete tag v3.1.3 and create a new one 3.2.0.

**Comment by evanvosberg** [comment]
The code it self didn't change only the release build is different. This means it's a big change in the repository but not in the distributed release code.

**Comment by jfroffice** [comment]
@evanvosberg I was thinking about the way to use the component with bower.

Think about it and the way you might use your component.

**Comment by evanvosberg** [comment]
All pre `3.1.3` versions have not bower support, but I understand your concerns.

From now the the tagged version is not just a dev state it's part of the release distribution. Of course I have to respect server for further changes not to break projects depending on this.
