### ISSUE TITLE
Please re-publish this package to npm

### ISSUE THREAD

**Issue by blankey1337** [brix/crypto-js#240]
This package hasn't been published in 3 years, and the version on npm currently is missing the important bug fix: https://github.com/brix/crypto-js/commit/7e4cf2f308a3eb3b848d6b9d0dd7b23736eb4aca

Can we please re-publish this to npm so that we can pull it into our projects? Thank you!

**Comment by herberthobregon** [comment]
@evanvosberg

**Comment by entronad** [comment]
@blankey1337 
@herberthobregon 
I am maintaining an alternative repo wich is just the same as crypto-js and written in ES6+ and with TypeScript support: [crypto-es](https://github.com/entronad/crypto-es) .
It has merged new commits including the 7e4cf2f PR.
You can try crypto-es from npm.

**Comment by evanvosberg** [comment]
Use the new version `3.2.0`
