### ISSUE TITLE
Help to maintaining the repo ?

### ISSUE THREAD

**Issue by macarthuror** [brix/crypto-js#246]
Hello,
I saw that some users are trying to improve the repo but there are not geting support.

Do you need help with that ?

**Comment by entronad** [comment]
@macarthuror 
There is an alternative for this repo, just the same as it and written in ECMAScript 6+ and with TypeScript support: [crypto-es](https://github.com/entronad/crypto-es) .
If you have any ideas, welcome to give issues or PRs !
