### ISSUE TITLE
after grunt build code error

### ISSUE THREAD

**Issue by SilkageNet** [brix/crypto-js#250]
`;(function (root, factory) {
	if (typeof exports === "object") {
		// CommonJS
		module.exports = exports = factory();
	}
	else if (typeof define === "function" && define.amd) {
		// AMD
		define([], factory);
	}
	else {
		// Global (browser)
		root.CryptoJS = factory();
	}
}(this, function () {

	return CryptoJS;

}));`

**Comment by evanvosberg** [comment]
This has been related to the change of lodash and the `this` context. 

Just fixed this.
