### ISSUE TITLE
[3.2.1] Unable to resolve module `crypto` from `node_modules/crypto-js/core.js`: crypto could not be found within the project.

### ISSUE THREAD

**Issue by Bardiamist** [brix/crypto-js#260]
I got
```
Unable to resolve module `crypto` from `node_modules/crypto-js/core.js`: crypto could not be found within the project.
```
when updated from `3.2.0` to `3.2.1`

**Comment by kishansbs** [comment]
same issue

**Comment by Malikkhoja-zz** [comment]
Same issue. We are using react-native-pdf and it has crypto-js as the dependency.

**Comment by evanvosberg** [comment]
Duplicate of https://github.com/brix/crypto-js/issues/256

Please help to verify whether this pull request https://github.com/brix/crypto-js/pull/259 would solve it.

**Comment by Bardiamist** [comment]
@evanvosberg 

I added in `package.json`:
```
"crypto-js": "git+https://github.com/brix/crypto-js.git#feature/react-native",
```

Then I tried to run project and got next red screen:
```
Unable to resolve module `crypto-js/hmac-sha512` from `src/global/api.ts`: crypto-js/hmac-sha512 could not be found within the project.

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules: rm -rf node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*

RCTFatal
__28-[RCTCxxBridge handleError:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
UIApplicationMain
main
start
```

I have
```
import hmacSHA512 from 'crypto-js/hmac-sha512';
```
in `src/global/api.ts`

**Comment by evanvosberg** [comment]
@Bardiamist did you run `grunt build` on this branch and then used the content of the `build` directory only?

The structure of the develop branch is not designed to be used directly. It's required to run `grunt build` in order to create a running package in the `build` directory.

@Bardiamist I would appreciate when you comment directly on the pull request, not here.

**Comment by gHashTag** [comment]
I do not use crypto, but I also use AWS Amplify with react-native. I get this error. How to fix?

**Comment by evanvosberg** [comment]
This issue is marked as `DUPLICATE`

Please leave your comments [here](https://github.com/brix/crypto-js/issues/256)

**Comment by imwilliamxy** [comment]
Same issue when upgrade from 3.1.9-1 to 4.0.0 used in react native project.

**Comment by hanykumar** [comment]
same issue with "crypto-js": "^4.0.0"

<img width="296" alt="Screenshot 2020-10-01 at 4 32 08 PM" src="https://user-images.githubusercontent.com/15860517/94801456-b1d6f600-0403-11eb-968e-a7a15e8af8be.png">

**Comment by Bardiamist** [comment]
Continued discussion here: https://github.com/brix/crypto-js/pull/259

**Comment by developeromI89** [comment]
facing same issue.  using Azure-blob-storage with React-Native

crypto could not be found within the project or in these directories:
  node_modules

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
   9 | var abortController = require('@azure/abort-controller');
  10 | var os = require('os');
> 11 | var crypto = require('crypto');
     |                       ^
  12 | var coreTracing = require('@azure/core-tracing');
  13 | var stream = require('stream');
  14 | require('@azure/core-paging');]
Error: Unable to resolve module crypto from azure\MyApp\node_modules\@azure\storage-blob\dist\index.js: crypto could not 
be found within the project or in these directories:
  node_modules

**Comment by bluego78** [comment]
same issue here

**Comment by Bardiamist** [comment]
https://github.com/brix/crypto-js/pull/259#issuecomment-799973769

**Comment by TheHexaflux** [comment]
when i updated "crypto-js" from '3.2.1' to "3.3.0", solved

**Comment by aaronNGJ5** [comment]
I found that react-native-crypto don't work on recent which using react-native version 0.62.2 and react version 16.11.0, any more.

I used crypto-js package. The version is 4.2.0 in my react-native app. It's working well on my side. 
You can add this in package.json, to try.

**Comment by Neustradamus** [comment]
Dear all: I have done an important announcement here:
- https://github.com/brix/crypto-js/issues/536

The solution is to replace by crypto-es:
- https://github.com/entronad/crypto-es
- https://github.com/entronad/crypto-es/tags
- https://github.com/entronad/crypto-es/releases
