### ISSUE TITLE
Sha256 in IE10 is not work;

### ISSUE THREAD

**Issue by nicetu** [brix/crypto-js#264]
sha256 in IE10 is not work;it will throw new Error('Secure random number generation is not supported by this browser.\nUse Chrome, Firefox or Internet Explorer 11');

**Comment by evanvosberg** [comment]
If this issue is about version 4.0.0, then it's not an issue. See the release notes, IE 10 is not supported in this version.

**Comment by nicetu** [comment]
> If this issue is about version 4.0.0, then it's not an issue. See the release notes, IE 10 is not supported in this version.
thanks,I know how to do fix it;

**Comment by nicetu** [comment]
> If this issue is about version 4.0.0, then it's not an issue. See the release notes, IE 10 is not supported in this version.

thanks,I know how to do fix it;
