### ISSUE TITLE
Error: Unable to resolve module `crypto` from

### ISSUE THREAD

**Issue by 90Mark** [brix/crypto-js#273]
crypto-js  use   version  @4.0.0

My project is reactnative，I'm just do...

1. npm install —-save crypto-js

2. import MD5 from 'crypto-js/md5'

And then,Is an error，The following information：

error: bundling failed: Error: Unable to resolve module `crypto` from `node_modules/crypto-js/core.js`: crypto could not be found within the project.

Please tell me what I should do，，Thank you very mucha

**Comment by Waitak** [comment]
I have this same issue, with the same version, running node v12.16.1. This is in an Angular 9 project. The `crypto` module is available in node:
```
% node
Welcome to Node.js v12.16.1.
Type ".help" for more information.
> require('crypto');
{
  createCipheriv: [Function: createCipheriv],
  createDecipheriv: [Function: createDecipheriv],
  createDiffieHellman: [Function: createDiffieHellman],
  createDiffieHellmanGroup: [Function: createDiffieHellmanGroup],
...
```

**Comment by ivandres** [comment]
I am having the same issue (Angular 9)

Module not found: Can't resolve 'crypto' in '..../node_modules/crypto-js'

**Comment by joaodematejr** [comment]
+1 I am having the same issue (React-Native 0.60)

**Comment by ingmaaguirre** [comment]
I am having the same issue (Angular 9)

WARNING in ./node_modules/crypto-js/core.js
Module not found: Error: Can't resolve 'crypto' in

**Comment by 90Mark** [comment]
resolved

use             "crypto-js": "3.1.9-1"

**Comment by 90Mark** [comment]
resolved

use "crypto-js": "3.1.9-1"

**Comment by marshall86** [comment]
using version 4.0.0, still there's the same problem

**Comment by Alanscut** [comment]
the latest version v4.0.0 has used secure random module, but *reactive-native* doesn't have the `crypto` module, the owner @evanvosberg is trying to fix this issue, detail in #259 , but still has some problem.

so if you want to use crypto-js in `react-native` project,  v3.1.9-1(or before) is a temporary choice before this issue has been fixed.

**Comment by hu-qi** [comment]
> the latest version v4.0.0 has used secure random module, but _reactive-native_ doesn't have the `crypto` module, the owner @evanvosberg is trying to fix this issue, detail in #259 , but still has some problem.
> 
> so if you want to use crypto-js in `react-native` project, v3.1.9-1(or before) is a temporary choice before this issue has been fixed.

![image](https://user-images.githubusercontent.com/17986122/77875844-ebc41580-7283-11ea-9ce9-6f38a1731e18.png)
I am having the same issue (React-Native 0.62)
I try to install ** v3.1.9-1** and it will work

**Comment by 90Mark** [comment]
thank you&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "huqi"<notifications@github.com&gt;; 
发送时间: 2020年3月30日(星期一) 中午12:47
收件人: "brix/crypto-js"<crypto-js@noreply.github.com&gt;; 
抄送: "1989329376"<1989329376@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [brix/crypto-js] Error: Unable to resolve module `crypto` from (#273)





  
the latest version v4.0.0 has used secure random module, but reactive-native doesn't have the crypto module, the owner @evanvosberg is trying to fix this issue, detail in #259 , but still has some problem.
 
so if you want to use crypto-js in react-native project, v3.1.9-1(or before) is a temporary choice before this issue has been fixed.
  

 I am having the same issue (React-Native 0.62)
 I try to install ** v3.1.9-1** and it will work

**Comment by entronad** [comment]
If the issues caused by secure radom of crypto-js 4.0 bother you, such as too large bundle, unavalible in React Native... Maybe you can try [crypto-es](https://www.npmjs.com/package/crypto-es) .

We merged all updates of crypto-js 4.0 except the secure radom.

**Comment by IamFlowZ** [comment]
Having this issue while setting up a react-native project, would be great to see a fix for this.

**Comment by HugoLiconV** [comment]
> Having this issue while setting up a react-native project, would be great to see a fix for this.

Me too, but the solutions that people shared solved the issue.

**Comment by Neustradamus** [comment]
Dear all: I have done an important announcement here:
- https://github.com/brix/crypto-js/issues/536

The solution is to replace by crypto-es:
- https://github.com/entronad/crypto-es
- https://github.com/entronad/crypto-es/tags
- https://github.com/entronad/crypto-es/releases
