### ISSUE TITLE
WTF with index.d.ts?

### ISSUE THREAD

**Issue by AlttiRi** [brix/crypto-js#279]
I used plain old [@types/cryptojs](https://www.npmjs.com/package/@types/cryptojs), but today I decide to check the new [@types/crypto-js](https://www.npmjs.com/package/@types/crypto-js) ([the repo](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/crypto-js)). And I was overwhelmed.

The `index.d.ts` says that `CryptoJS.AES.decrypt` params are 

```ts
    encryptedMessage: string | WordArray,
    secretPassphrase: string | WordArray,
    option?: CipherOption)
```
Well, okay. Changing `CipherParamsData` to `WordArray` is even good (Only `ciphertext` property (`WordArray`) of `CipherParamsData` is used, the other are ignored.), no need to wrap `WordArray` to an object. (UPD: It is fake too! There is no support to passing the normal `WordArray` as `encryptedMessage`). But stop...
The `index.d.ts` says that `WordArray` is 

```ts
	export interface WordArray {
		iv: string;
		salt: string;
		ciphertext: string;
		key?: string;
		toString(encoder?: Encoder): string;
	}
```
What? The array of 32 bits words (integers) is an object with string properties now? It's absolutely non sense naming (renaming). If I have a `Uint8Array` I should convert it to a string now, in order to pass it to `decrypt`? 
Why? CryptoJS works with `WordArray` (I mean the normal `WordArray`) inside.
It forces to do 2 conversions (`Uint8Array` -> `String` -> `WordArray`), instead one (`Uint8Array` -> `WordArray`).

Let's check the other thing, I use the code that creates the plain old `WordArray` that I pass to `decrypt`:
```js
        /**
         * The convert code [*] is from "crypto-js/lib-typedarrays.js" file
         * @param {Uint8Array} arrayBuffer
         * @returns {CryptoJS.lib.WordArray} wordArray
         * @private
         */
        const _arrayBufferToWordArray = function(arrayBuffer) {
            const words = [];
            for (let i = 0; i < arrayBuffer.length; i++) {
                words[i >>> 2] |= arrayBuffer[i] << (24 - (i % 4) * 8); // [*]
            }
            return CryptoJS.lib.WordArray.create(words, arrayBuffer.length);
        };
```

But IDE shows me the warning based on the new `index.d.ts`. `index.d.ts` says:
```ts
		lib: {
			WordArray: {
				create: (v: any) => LibWordArray;
				random: (v: number) => WordArray;
			};
		};
```
Plain old `WordArray` now is `LibWordArray`, but: `create: (v: any) => LibWordArray`. "`(v: any)`", really?

The old, and the **right** signature is 
`create(words?: number[], sigBytes?: number): WordArray`.
_(Should note, that there is also `create(typedArray: SomeArray): WordArray`, but it does not work, I get the exception `RangeError: Source is too large` when I pass `Uint8Array`)._

`create` returns `LibWordArray`, but `random` returns **the other type** `WordArray`. Well...

I use in my code only 2 methods of CryptoJS, and both have the wrong signatures with the new `index.d.ts`, that is about other methods?

Should say [@types/cryptojs](https://www.npmjs.com/package/@types/cryptojs) is still actual and better.

**Comment by AlttiRi** [comment]
Here is how it should be (based on `@types/cryptojs`):
**Note: `lib.WordArray` and `WordArray` are the same thing.**
```ts
declare var CryptoJS: CryptoJS.CryptoJSStatic;
declare namespace CryptoJS {
        namespace lib {
                interface Base { ... }
                interface WordArray extends Base {
                        words: number[]
                        sigBytes: number
                        create(typedArray: SomeArray): WordArray;
                        create(words?: number[], sigBytes?: number): WordArray
                        ...
                }
                interface CipherParamsData {
                        ciphertext?: lib.WordArray
                        key?: lib.WordArray
                        iv?: lib.WordArray
                        salt?: lib.WordArray
                        ...
                }
                interface CipherParams extends Base, CipherParamsData {
                        init(cipherParams?: CipherParamsData): void
                        create(cipherParams?: CipherParamsData): CipherParams
                        toString(formatter?: format.IFormatter): string
                }
                interface IBlockCipherCfg {
                        iv?: WordArray;
                        mode?: mode.IBlockCipherModeImpl //default CBC
                        padding?: pad.IPaddingImpl //default Pkcs7
                }
                interface ICipherHelper<C> { // `C` is `IBlockCipherCfg` for `AES`
                        encrypt(message: string,    password: string, cfg?: C): CipherParams
                        encrypt(message: string,    key: WordArray, cfg?: C): CipherParams
                        encrypt(message: WordArray, password: string, cfg?: C): CipherParams
                        encrypt(message: WordArray, key: WordArray, cfg?: C): CipherParams

                        decrypt(ciphertext: string, password: string, cfg?: C): WordArray
                        decrypt(ciphertext: string, key: WordArray, cfg?: C): WordArray
                        decrypt(ciphertext: CipherParamsData, password: string, cfg?: C): WordArray
                        decrypt(ciphertext: CipherParamsData, key: WordArray, cfg?: C): WordArray
                }
        }
        interface CryptoJSStatic {
                AES: CryptoJS.lib.ICipherHelper<CryptoJS.lib.IBlockCipherCfg>
        }
}
```

Renaming `CipherParamsData` and `CipherParams` to `WordArray` is the most stupid (re-)naming I have even seen. It's better name it `Foo` or `Bar`, in this case the name is no misleading.

**Comment by AlttiRi** [comment]
The old [index.d.ts is here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/cryptojs/index.d.ts). It's just one file that works well. 
You can also take a look at [CryptoES](https://github.com/entronad/crypto-es). It has the well written [index.d.ts](https://github.com/entronad/crypto-es/blob/master/lib/index.d.ts).

**Comment by yangfanyu** [comment]
Good title hahahaha!
