### ISSUE TITLE
A bug 

### ISSUE THREAD

**Issue by Iezuni** [brix/crypto-js#310]
using 
```
import cryptoJS from "crypto-js";
cryptoJS.enc.Base64.stringify("ab"),
```
error Info:
Uncaught TypeError: wordArray.clamp is not a function

**Comment by Asinox** [comment]
let data = CryptoJS.enc.Utf8.parse('ab');
CryptoJS.enc.Base64.stringify(data);

**Comment by Iezuni** [comment]
> let data = CryptoJS.enc.Utf8.parse('ab');
> CryptoJS.enc.Base64.stringify(data);

It's worked
thank you

**Comment by miladganjali** [comment]
@yinyunsan  Please close Issue

**Comment by karimkozman** [comment]
> let data = CryptoJS.enc.Utf8.parse('ab');
CryptoJS.enc.Base64.stringify(data);
@Asinox

But how do you decrypt it back to the original text? I tried this example but it returns `[object Object]`:

```
const decrypt = (data) => {
  return CryptoJS.enc.Base64.parse(data).toString(CryptoJS.enc.Utf8);
};
```
