### ISSUE TITLE
Does not work with Open SSL private keys

### ISSUE THREAD

**Issue by AllanOricil** [brix/crypto-js#315]

**Comment by AllanOricil** [comment]
I put my key in one line, without any spaces and it also did not work. Then I reduced the key size and it worked. Is there a limit for the key size?

**Comment by AllanOricil** [comment]
My server response with the message and the encrypted message.


![image](https://user-images.githubusercontent.com/55927613/91679023-7a7fdb80-eb1d-11ea-92b1-49ef8525bfd1.png)

Pick the private key above and try to decrypt the encrypted message 
```
U2FsdGVkX1+1OU4OEjcXAZ9iJxxce/SWVTFNkShW0QTXExgBFyiJ7pHTZ9miEDxIWRBtv0J8V3ydzLGJSvBzwrOsZSzzvY6Mm8bxBiRqo9tgiZw+hmcgToijyfQKRG/2zVkufIimLI+1F977kLfVpA==
```

It will return a BLANK string. 

![image](https://user-images.githubusercontent.com/55927613/91679201-faa64100-eb1d-11ea-8946-912574dfc818.png)


The Expected result was
```
5Aep861OVg8QiCb44ByDkG6vdPo8AkeO5Tgs9O7gGeOlF4jqpNjDWT4BVDXR9z07Vn9fKo915Ue.1EePGnzyWiZ
```

**Comment by secure12** [comment]
Why would you use your RSA private key as the AES encryption key?

**Comment by AllanOricil** [comment]
> Why would you use your RSA private key as the AES encryption key?

@secure12 Because I already have it inside my server and I did not want to create another key to encrypt the messages. Why do you ask it? Is it a bad idea? And why the lib does not work with it?

**Comment by ozyman42** [comment]
> > Why would you use your RSA private key as the AES encryption key?
> 
> @secure12 Because I already have it inside my server and I did not want to create another key to encrypt the messages. Why do you ask it? Is it a bad idea? And why the lib does not work with it?

You should be encrypting via public key and decrypting via private key. If you encrypt via private key than anyone with the public key can decrypt.
