### ISSUE TITLE
Decrypt stopped to work after update

### ISSUE THREAD

**Issue by tomaszzmudzinski** [brix/crypto-js#320]
Hi guys, I am wondering why this not work after @crypto-js@4.0.0 and @types/crypto-js@4.0.0 upgrade:

`return CryptoJS.AES.decrypt(textToDecrypt, SECRET_KEY.trim()).toString(CryptoJS.enc.Utf8);`

![image](https://user-images.githubusercontent.com/4519335/94991642-b676e800-0584-11eb-8e17-e183c1a3096a.png)

Could you tell me how to make it work after the library update?

**Comment by itcat99** [comment]
same

**Comment by berviantoleo** [comment]
I meet the same problem. Any one have an update for this?

**Comment by hieplpvip** [comment]
See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47687#issuecomment-703143148

**Comment by berviantoleo** [comment]
Seems still not work for me. Maybe have different expected input from the decrypt()

![image](https://user-images.githubusercontent.com/15927349/95067565-3be9cc00-072e-11eb-9ef6-f86d673152e3.png)

**Comment by mymindstorm** [comment]
I think what everyone here wants is:

```js
return CryptoJS.AES.decrypt(textToDecrypt, SECRET_KEY.trim()).toString();
```

https://github.com/brix/crypto-js/blob/90884e679206162183b979067209d51668e4751d/src/cipher-core.js#L538-L555

**Comment by hieplpvip** [comment]
@mymindstorm I tried it but it didn't work

**Comment by mymindstorm** [comment]
> @mymindstorm I tried it but it didn't work

Without `ciphertext`?

**Comment by berviantoleo** [comment]
@mymindstorm ,

Yeah, something like that. But,

```javascript
return CryptoJS.AES.decrypt(textToDecrypt, SECRET_KEY.trim()).toString();
```

Give me the hex string. I need to convert again to Utf8.

Different with previous version, which we can use this,

```javascript
return CryptoJS.AES.decrypt(textToDecrypt, SECRET_KEY.trim()).toString(CryptoJS.enc.Utf8);
```

**Comment by SevenOutman** [comment]
Looks like an issue with the type definition, please follow https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47687#issuecomment-704075040 and https://github.com/DefinitelyTyped/DefinitelyTyped/issues/48460.

**Comment by SevenOutman** [comment]
It's been fixed in `@types/crypto-js@4.0.1` (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/48533).

**Comment by hieplpvip** [comment]
Confirm fixed. Thanks a lot.

**Comment by Neustradamus** [comment]
Dear all: I have done an important announcement here:
- https://github.com/brix/crypto-js/issues/536

The solution is to replace by crypto-es:
- https://github.com/entronad/crypto-es
- https://github.com/entronad/crypto-es/tags
- https://github.com/entronad/crypto-es/releases
