### ISSUE TITLE
webpack 5 warning "Module not found: Error: Can't resolve 'crypto'".

### ISSUE THREAD

**Issue by Directory** [brix/crypto-js#326]
both dev and production builds leave this warning. im importin a few modules such as sha1 etc. in my case the application code is meant for browser execution only.
```
WARNING in ./node_modules/crypto-js/core.js 43:22-39
Module not found: Error: Can't resolve 'crypto' in 'D:\redacted\node_modules\crypto-js'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
        - install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "crypto": false }
 @ ./node_modules/crypto-js/sha1.js 4:37-54
 @ ./redacted/script.js 6:0-34 36:12-16
```
besides this the build works fine. its just a warning like it says. im not entirely sure what this means and i only started using it in webpack after i update to 5 so i don't know if this was a problem before. how can i get rid of this error, should i bother?

**Comment by Directory** [comment]
nvm. fixed when i spend half a second and actually read what it tells me to do. i updated `resolve` to have
```js
resolve: {
    fallback: {
      "crypto": false
    }
  }
```
if this polyfill is meant for node execution or whatever then its not needed for my browser only purposes.

**Comment by karanfulare** [comment]
Should I add this change to the file ./node_modules/react-scripts/config/webpack.config.js  near line 304
