### ISSUE TITLE
Question: Is AES using 256-bit encryption?

### ISSUE THREAD

**Issue by jinxx0** [brix/crypto-js#327]

**Comment by HarveyRDonnelly** [comment]
Yes and no. 256-bit AES is supported by crypto-js but it is not always used.

**Please note the official crypto-js documentation below:**
> CryptoJS supports AES-128, AES-192, and AES-256. It will pick the variant by the size of the key you pass in. If you use a passphrase, then it will generate a 256-bit key.

I hope this answers your question.
