### ISSUE TITLE
cryptojs problem in nuxtjs when runn :" nnpm run build"

### ISSUE THREAD

**Issue by YallaDealz** [brix/crypto-js#332]
ERROR in ./services/crypt.service.ts
Module not found: Error: Can't resolve 'crypto-js' in '/home/yalladealz/Frontend/services'
 @ ./services/crypt.service.ts 6:0-48 15:13-16 20:13-16 20:69-72 28:6-9 29:8-12 30:11-14
 @ ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./pages/login/index.vue?vue&type=script&lang=js&
 @ ./pages/login/index.vue?vue&type=script&lang=js&
 @ ./pages/login/index.vue
 @ ./.nuxt/router.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js

ERROR in services/crypt.service.ts:1:31
TS2305: Module '"../node_modules/@types/crypto-js"' has no exported member 'CipherOption'.
  > 1 | import { AES, enc, mode, pad, CipherOption } from 'crypto-js'
      |                               ^^^^^^^^^^^^
    2 |
    3 | export class CryptService {
    4 |   private static secret: string = 'CIPHERKEY'

**Comment by waziaq** [comment]
@YallaDealz How did you set up this plugin on NuxtJs? Can teach me?
