### ISSUE TITLE
CryptoJS.AES.decrypt with mode and vi not working 

### ISSUE THREAD

**Issue by Gajendrasinh** [brix/crypto-js#336]
Hello,

I am using below two function for  encrypt & decrypt

My plain test is just "Test" but while i am decrypt this getting 54657374 can anyone having same issue ?

```
encryptKey(text: any) {
    var rkEncryptionKey = CryptoJS.enc.Base64.parse('Q?HY4lokdhKghesthN5xl3j==');
    var rkEncryptionIv = CryptoJS.enc.Base64.parse('8T7e3SWmHRRlkj56/gIN3q==');
    var utf8Stringified = CryptoJS.enc.Utf8.parse(text);
    var encrypted = CryptoJS.AES.encrypt(utf8Stringified.toString(), rkEncryptionKey, { mode: CryptoJS.mode.CBC, iv: rkEncryptionIv });

    return encrypted.toString()
  }

  decryptKey(text: any) {
     var rkEncryptionKey = CryptoJS.enc.Base64.parse('Q?HY4lokdhKghesthN5xl3j==');
    var rkEncryptionIv = CryptoJS.enc.Base64.parse('8T7e3SWmHRRlkj56/gIN3q==');
    var decrypted = CryptoJS.AES.decrypt(text, rkEncryptionKey, { mode: CryptoJS.mode.CBC, iv: rkEncryptionIv });
    return decrypted.toString(CryptoJS.enc.Utf8)
  }
```

**Comment by kg-currenxie** [comment]
I have the same problem. Here's my example

```
import C from 'crypto-js'
import AES from 'crypto-js/aes'
import Hex from 'crypto-js/enc-hex'
import Utf8 from 'crypto-js/enc-utf8'
import ECB from 'crypto-js/mode-ecb'

const SECRET = '48656c6c6f2c20576f726c6421'

const IV = Hex.parse('00000000000000000000000000000000')
const wordArraySecret = Hex.parse(SECRET)

const round = {
  answer: 'SE',
  guess: 'SE',
  roundStartTimestamp: 1000,
  guessTimestamp: 2000,
}

export function testEncrypt(): void {
  const jsonString = JSON.stringify(round)
  const parsedJson = Utf8.parse(jsonString)
  const enc = AES.encrypt(parsedJson, wordArraySecret, {
    iv: IV,
    mode: ECB,
  }).toString()

  // sendEncToServer()

  // -- Below will be decrypted on the server

  const data = Hex.parse(enc)

  const encrypted = {} as C.lib.CipherParams
  encrypted.key = wordArraySecret
  encrypted.iv = IV
  encrypted.ciphertext = data

  const decrypted = AES.decrypt(encrypted, wordArraySecret, {
    iv: IV,
    mode: ECB,
  })

  console.log({ round, parsedJson })
  console.log({ enc })
  console.log({ data })
  console.log(decrypted.toString())
}
```

Output

```
[Mon Mar 22 2021 22:58:18.418]  LOG      {"parsedJson": {"sigBytes": 77, "words": [2065850734, 1937204594, 574235219, 1159867426, 1735746931, 1931622946, 1397039660, 577924981, 1852068724, 1634890836, 1768777075, 1952542064, 574239024, 808463394, 1735746931, 1934911853, 1702065249, 1836065338, 842018864, 2097152000]}, "round": {"answer": "SE", "guess": "SE", "guessTimestamp": 2000, "roundStartTimestamp": 1000}}
[Mon Mar 22 2021 22:58:18.419]  LOG      {"enc": "WZqe835CmpjntyC77pI54HOJTD5ycWtqCeb26IHjhuLqfmc2y9lYWuNxOt8DHezaMjotkOGNKKoabjuBBr8E0RnD4/ozzyM2/fmPWHNB2h4="}
[Mon Mar 22 2021 22:58:18.419]  LOG      {"data": {"sigBytes": 54, "words": [33628, 199, 117441536, 330752, -827193856, 4034, 0, 9240576, 0, 2816, 193855488, 67108864, 0, 33816576]}}
[Mon Mar 22 2021 22:58:18.420]  LOG      6bce3e3f57af785ac6eec7f64b07e42f2c
```

Expected:
` "{\"answer\":\"SE\",\"guess\":\"SE\",\"roundStartTimestamp\":1000,\"guessTimestamp\":2000}"`

Actual: 
`6bce3e3f57af785ac6eec7f64b07e42f2c`

Not sure what I'm missing :)

**Comment by ytianzaishui** [comment]
> I have the same problem. Here's my example
> 
> ```
> import C from 'crypto-js'
> import AES from 'crypto-js/aes'
> import Hex from 'crypto-js/enc-hex'
> import Utf8 from 'crypto-js/enc-utf8'
> import ECB from 'crypto-js/mode-ecb'
> 
> const SECRET = '48656c6c6f2c20576f726c6421'
> 
> const IV = Hex.parse('00000000000000000000000000000000')
> const wordArraySecret = Hex.parse(SECRET)
> 
> const round = {
>   answer: 'SE',
>   guess: 'SE',
>   roundStartTimestamp: 1000,
>   guessTimestamp: 2000,
> }
> 
> export function testEncrypt(): void {
>   const jsonString = JSON.stringify(round)
>   const parsedJson = Utf8.parse(jsonString)
>   const enc = AES.encrypt(parsedJson, wordArraySecret, {
>     iv: IV,
>     mode: ECB,
>   }).toString()
> 
>   // sendEncToServer()
> 
>   // -- Below will be decrypted on the server
> 
>   const data = Hex.parse(enc)
> 
>   const encrypted = {} as C.lib.CipherParams
>   encrypted.key = wordArraySecret
>   encrypted.iv = IV
>   encrypted.ciphertext = data
> 
>   const decrypted = AES.decrypt(encrypted, wordArraySecret, {
>     iv: IV,
>     mode: ECB,
>   })
> 
>   console.log({ round, parsedJson })
>   console.log({ enc })
>   console.log({ data })
>   console.log(decrypted.toString())
> }
> ```
> 
> Output
> 
> ```
> [Mon Mar 22 2021 22:58:18.418]  LOG      {"parsedJson": {"sigBytes": 77, "words": [2065850734, 1937204594, 574235219, 1159867426, 1735746931, 1931622946, 1397039660, 577924981, 1852068724, 1634890836, 1768777075, 1952542064, 574239024, 808463394, 1735746931, 1934911853, 1702065249, 1836065338, 842018864, 2097152000]}, "round": {"answer": "SE", "guess": "SE", "guessTimestamp": 2000, "roundStartTimestamp": 1000}}
> [Mon Mar 22 2021 22:58:18.419]  LOG      {"enc": "WZqe835CmpjntyC77pI54HOJTD5ycWtqCeb26IHjhuLqfmc2y9lYWuNxOt8DHezaMjotkOGNKKoabjuBBr8E0RnD4/ozzyM2/fmPWHNB2h4="}
> [Mon Mar 22 2021 22:58:18.419]  LOG      {"data": {"sigBytes": 54, "words": [33628, 199, 117441536, 330752, -827193856, 4034, 0, 9240576, 0, 2816, 193855488, 67108864, 0, 33816576]}}
> [Mon Mar 22 2021 22:58:18.420]  LOG      6bce3e3f57af785ac6eec7f64b07e42f2c
> ```
> 
> Expected:
> ` "{\"answer\":\"SE\",\"guess\":\"SE\",\"roundStartTimestamp\":1000,\"guessTimestamp\":2000}"`
> 
> Actual:
> `6bce3e3f57af785ac6eec7f64b07e42f2c`
> 
> Not sure what I'm missing :)

Have you resolved this issue,I wonder what's caused this problem.

**Comment by kg-currenxie** [comment]
No :/ Decided to switch the library to `node-forge`, and used their public/private key encryption.

**Comment by scottoverend** [comment]
Also having the same problem unfortunately
