### ISSUE TITLE
How to use in IE11 (using webpack v5, babel-loader)

### ISSUE THREAD

**Issue by KaminoRyo** [brix/crypto-js#344]
I'm sorry, it's not strictly a crypto-js issue.😟
However, it is too difficult to output for IE11 using Webpack 5, babel 7, so please give me some advice.
Or you may write it in the manual.

Oh,In Webpack5 I have to install polyfill of node.js module myself.
Crypto-js requires "buffer", "crypto-browserify", "stream-browserify".
(webpack told me in a console message)

The is package.json.

```json
 "devDependencies": {
    "@babel/core": "^7.13.10",
    "@babel/preset-env": "^7.13.10",
    "@types/crypto-js": "^4.0.1",
    "@typescript-eslint/eslint-plugin": "^4.17.0",
    "@typescript-eslint/parser": "^4.17.0",
    "babel-loader": "^8.2.2",
    "eslint": "^7.22.0",
    "npm-check-updates": "^11.3.0",
    "ts-loader": "^8.0.18",
    "typescript": "^4.2.3",
    "webpack": "^5.25.1",
    "webpack-cli": "^4.5.0",
  },
  "dependencies": {
    "buffer": "^6.0.3",
    "core-js": "^3.9.1",
    "crypto-browserify": "^3.12.0",
    "crypto-js": "^4.0.0",
    "stream-browserify": "^3.0.0"
  },
```

An error has occurred in the Exponentiation operator ("**") of the "buffer" library only during production build.
For some reason it works with a development build.🙄

This is webpack.config.js. 
```js
	rules:[
	{
		test: /\.ts$/,
		use: [
			{
			loader: "babel-loader",
			options: {
				presets: [
					[
						"@babel/preset-env",
						{
							"modules": false,
							"targets": { "ie": "11" },
							'useBuiltIns': 'usage',
							'corejs': 3
						}
					]
				]
			}
			},
			{
				loader: 'ts-loader',
				options: { transpileOnly: true }
			}
		],
		exclude: /node_modules/
	}],
	resolve: {
		extensions: [".ts", ".js"],
		fallback: {
		"crypto": require.resolve("crypto-browserify"),
		"buffer": require.resolve("buffer/"),
		"stream": require.resolve("stream-browserify"),
		}
	},
	target: ["web", "es5"]
```

I gave up once. 😫 I'm going back to old version, but I have to solve it someday.

**Comment by Hinaser** [comment]
Hi
You can try https://www.npmjs.com/package/jscrypto for crypto-js enhancement.
I tested that this `jscrypto` works in IE11 with webpack5.
Hope this can help.

**Comment by dkaus1** [comment]
Hi, I'm also facing similar issue however buffer dependency is being used in node_modules/webpack/lib/serialization/FileMiddleware.js . Final bundle showing same error as above in IE11 . Any clue what could be the fix for same?
