### ISSUE TITLE
Please drop requirement on nodejs

### ISSUE THREAD

**Issue by nirgal** [brix/crypto-js#36]
I'm using crypto-js without nodejs nor require nor whatever.
This works quite well.

It would be nice if the documentation would stop pretending this is a requirement. I guess it frightens people. Plus there is an example on https://github.com/brix/crypto-js that starts with `var CryptoJS = require("crypto-js");` that makes things look impossible to use, especially with free software.

Roll ups like the one on that were available on google were much better in my opinion...

**Comment by evanvosberg** [comment]
It doesn't depend on NodeJS. 

CryptoJS is shipped as `UMD` (Universal Module Definition) to work with main standards of JavaScript module definitions. 
- `CommonJS` used in NodeJS ... and others
- `AMD` (Asynchronous Module Definition) used in RequireJS, Angular ... and others

Btw. `CommonJS` and `AMD` are open standards, you can build your own implementation or just use a framework for, most are _free software_ licensed under MIT.

Of course it's possible to use CryptoJS in a way of global definitions like `window.CryptoJS =`, but this not state of the art, it's more like stuck in the 90s.

**Comment by nirgal** [comment]
Uh?
When one read https://github.com/brix/crypto-js it looks like you need nodejs, in my opinion:
I mean the "nodejs (install)" seems to indicate you need nodejs to install it.
The "requirement: nodejs" is in a section, right, but it's highly confusing.
The "Client (browser)" section also says "Requirements: nodejs"
There is a full example section, it start with "var CryptoJS = require("crypto-js");" which just does not work out of the box.

So maybe I'm "stuck in the 90s" like you say, but I'm pretty sure it would be really nice to be able use a plain and simple `script src=foo/crypto.js` in web sites.
It used to be the case when the code was at google. I do miss that.
I bet I'm not the only one on earth to use javascript that way, hence the request.

**Comment by kdqed** [comment]
Its 2020 and I'm "still stuck in 90s", one upping a request for this.
