### ISSUE TITLE
Error using 4.1.0 version

### ISSUE THREAD

**Issue by felixzapata** [brix/crypto-js#365]
Hi, after update the package to the 4.0.1 version I have this error on the browser:

![Captura de pantalla 2021-07-22 a las 13 18 41](https://user-images.githubusercontent.com/997038/126631369-ba568291-3b3e-4c56-b72d-353bf423e22a.png)

related with this one:

![Captura de pantalla 2021-07-22 a las 13 21 46](https://user-images.githubusercontent.com/997038/126631566-eb1d8d62-de94-4fea-9242-875b5c1e74c4.png)

`Uncaught TypeError: StreamCipher is undefined`

**Comment by evanvosberg** [comment]
Just fixed in `4.1.1`

**Comment by alberthuang24** [comment]
Why can't I find `4.1.1` in [this](https://github.com/brix/crypto-js/releases) ?
