### ISSUE TITLE
after update of crypto-js version from 4.0.0 to 4.1.1, React JS app is not loading in IE

### ISSUE THREAD

**Issue by lakshmiekula** [brix/crypto-js#368]
In IE browser, I can see error SCRIPT1006: Expected ')'
Below is screenshot for same
![image](https://user-images.githubusercontent.com/10266791/127132605-1bcc25a8-f148-4557-8fdd-ad405c35873f.png)
Please help to fix this issue.

**Comment by evanvosberg** [comment]
This is because IE can't deal with default values for arguments.

I do not consider IE support, even not IE 11. Major websites such as Twitter, YouTube, Slack, Microsoft 365 ... already dropped IE 11.

If you can't live with IE support, stay on `4.0.0`.
