### ISSUE TITLE
License file is not included in the NPM package

### ISSUE THREAD

**Issue by Pashokus** [brix/crypto-js#39]
Please add these files with full license text to the NPM distribution packages. Unfortunately, from the legal standpoint, simply specifying the name of the license is not enough, because it's unclear where to get the EXACT (legally binding) text of that license. This is a major roadblock on our way to using the module, seriously.

Thanks a lot for the great code, and thanks in advance for fixing this blocker.

**Comment by evanvosberg** [comment]
Thanks for the hint. Will add it and it will be part of the next release ;)

**Comment by evanvosberg** [comment]
Solved with v3.1.6
