### ISSUE TITLE
How to import a md5 hash object from json?

### ISSUE THREAD

**Issue by legionaryu** [brix/crypto-js#42]
I have this json:
"hashMix": {
    "words": [
      -699555019,
      -1289234862,
      1459631473,
      -802739593
    ],
    "sigBytes": 16
  }

And I want to parse it to the Hash (Base) object, how is the best way to do it?

**Comment by evanvosberg** [comment]
Sorry, just don't get it. What are you exactly trying to do?

**Comment by legionaryu** [comment]
I want to make something like this command line in linux
find somedir -type f -exec md5sum {} \; | sort -k 34 | md5sum
but I want to be able to recover from a crash, by saving the current hash on a json file.

**Comment by legionaryu** [comment]
I read the source and found a solution:

``` javascript
var CryptoJS = require("crypto-js");
var MD5 = CryptoJS.MD5;
var hashMix = CryptoJS.lib.WordArray.init(jsonObj.hashMix.words, jsonObj.hashMix.sigBytes);
console.log(MD5(fileData, hashMix));
```

**Comment by evanvosberg** [comment]
Cool, just try this way as well but you found it by your own.
