### ISSUE TITLE
jmeter Cannot load script from crypto-js-3.2.1.js

### ISSUE THREAD

**Issue by duxuebing** [brix/crypto-js#426]
jmeter JSR223 Sampler
load("crypto-js.js");

Response code:500
Response message:javax.script.ScriptException: TypeError: Cannot load script from crypto-js-3.2.1.js in <eval> at line number 2

**Comment by duxuebing** [comment]
> jmeter JSR223 Sampler load("crypto-js.js");
> 
> Response code:500 Response message:javax.script.ScriptException: TypeError: Cannot load script from crypto-js-3.2.1.js in at line number 2

**Comment by duxuebing** [comment]
that's it
load("/Users/apple/Library/apache-jmeter-5.4.3/bin/crypto-js-3.1.9/crypto-js.js");

**Comment by lx2324268860** [comment]
> that's it load("/Users/apple/Library/apache-jmeter-5.4.3/bin/crypto-js-3.1.9/crypto-js.js");

perfect
