### ISSUE TITLE
Error: this package doesn't seem to provide a ESM version

### ISSUE THREAD

**Issue by HuakunShen** [brix/crypto-js#428]
It doesn't work within a ESM module.

`index.mjs`:

```js
import sha256 from "crypto-js/sha256";
console.log(sha256("message"));
```

Error: 
```
node:internal/process/esm_loader:94
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/app/node_modules/crypto-js/sha256' imported from /app/index.mjs
Did you mean to import crypto-js/sha256.js?
```

The code works when I am using commonjs.

**Comment by pi0** [comment]
(This is not exactly answering your question or suggest as replacement solution for this package.)

Recently I've extracted ESM friendly and tree-shaken version of SHA256 crypto-js into [unjs/ohash](https://github.com/unjs/ohash) you could use.

**Comment by hungtcs** [comment]
@HuakunShen I have a clone refactor with typescript and esmodule

- https://github.com/hungtcs/escrypto

**Comment by entronad** [comment]
Maybe you could try [CryptoES](https://github.com/entronad/crypto-es), it is originally written in ES6 module, and with same code with CryptoJS inside.

**Comment by nwalters512** [comment]
This will work if you explicitly specify the extension:

```ts
import sha256 from "crypto-js/sha256.js";
```

**Comment by JavascriptMick** [comment]
worked for me if I imported the types...

package.json
```json
  {
  "type": "module",
  "devDependencies": {
    "@types/crypto-js": "^4.2.2"
    }
   }
  ```
  
  and imported with the .js ext
  ```ts
  import sha256 from 'crypto-js/sha256.js';
  ```
