### ISSUE TITLE
Add CryptoJS to AngularJS App

### ISSUE THREAD

**Issue by ghost** [brix/crypto-js#44]
I installed with   bower install crypto-js --save  
But i do not know how to add or use in my angular application
1. I tried adding  angular.module('myApp',[..,...,...,.., 'crypto-js'])
2. I tried adding  angular.module('myApp',[..,...,...,.., 'CryptoJS'])
crypto-js and CryptoJS does not work.
How can i add "crypto-js" to myApp ?
Thanks.

**Comment by needforspeed** [comment]
CryptoJS should work. and it's a global variable.

**Comment by mscahill** [comment]
For me, the global variable CryptoJS was 'undefined'. To get it to work, I had to override "main" in the bower.json of my app:

"overrides": {
    "crypto-js": {
      "main": "crypto-js.js"
    }
  }

**Comment by evanvosberg** [comment]
Does Angular has proper AMD support like RequireJS?

**Comment by cullsin** [comment]
Hi, 

We are also trying to Implement in Angular 1.x. Can you suggest me where to we override "main" in bower configuration OR how can we use in angular ?

Thanks,
Raja K

**Comment by jsandeepm** [comment]
Hi,
CryptoJS is working fine in my angular application but in console we see the below error

![image](https://user-images.githubusercontent.com/9821180/80704532-60e46e00-8b02-11ea-8817-cfaa024e6d59.png)
