### ISSUE TITLE
Converting circular structure to JSON

### ISSUE THREAD

**Issue by arunlals** [brix/crypto-js#45]
Hi,

I installed crypro js and was trying to do AES encrypt as follows.

var userAES = CryptoJS.AES.encrypt(JSON.stringify(info.user), 'thisisakey');

But it says "Unhandled rejection TypeError: Converting circular structure to JSON"

**Comment by evanvosberg** [comment]
This means your json can't be stringified ... it's not related to Crypto-JS.

**Comment by arunlals** [comment]
I can console.log(JSON.stringify(info.user)); and its working fine. See my code below.

> console.log(JSON.stringify(info.user));
> // var userAES = CryptoJS.AES.encrypt(JSON.stringify(info.user), 'thisisakey');

**Comment by evanvosberg** [comment]
Pretty strange because the error message is related to the `JSON.stringify()`.

**Comment by havenchyk** [comment]
@arunappulal have you solved it? I have the same.

**Comment by sarahsga** [comment]
When you
`var userAES = CryptoJS.AES.encrypt(JSON.stringify(info.user), 'thisisakey');`

you must not
`JSON.stringify(userAES);`

**Comment by FascistDonut** [comment]
I have this exact same issue when trying to use the sample script:

`var CryptoJS = require("crypto-js");
 
var data = [{id: 1}, {id: 2}]
 
// Encrypt 
var ciphertext = CryptoJS.AES.encrypt(JSON.stringify(data), 'secret key 123');
 `

Always has " Converting circular structure to JSON" error.

**Comment by nhoctanker** [comment]
+1 we got same issue

**Comment by TurningTide** [comment]
```
let configString = JSON.stringify(param[key]); //fine
let encryptedString = CryptoJS.AES.encrypt(configString, 'thekey') // Converting circular structure to JSON
```

Same issue at september 2019 😭

**Comment by joshua-schwartz** [comment]
Same issue Feb 2021.

CryptoJS gives us this issue, but not CryptoES. Same input data. Confirmed it is getting properly stringified. No errors until it hits the `encrypt()`.

```return CryptoJS.AES.encrypt(JSON.stringify(rawData), encryptKey)```
^ doesn't work

```return CryptoES.AES.encrypt(JSON.stringify(rawData), encryptKey)```
^ works

**Comment by joshua-schwartz** [comment]
We were only able to resolve this issue by switching to the CryptoES library. Not sure if this one is even actively maintained anymore.

**Comment by zbagley** [comment]
For those of you hitting this issue, there's a good chance that you're using a CryptoJS **CipherParams** rather than the string you're probably looking for. Quick fix is to call `.toString()` or `.toString(<encoding type>)` to get the actual string object rather than the attempting to work with the **CipherParams** after calling `AES.encrypt(...)`.
