### ISSUE TITLE
 Converts a Base64 string to a word array - CryptoJS.enc.Base64.parse(str64) - IndexOf error

### ISSUE THREAD

**Issue by VM999** [brix/crypto-js#46]
Here's my code :
`var CryptoJS = require("crypto-js");

var key = '5024D151B40D7F5724B5563A316938C5';
var aBlock = [ 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
                          ];
var sBlock = [ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
                          ];
var sBlock_str64 = CryptoJS.AES.encrypt(aBlock.join(""), key);
        console.log("sBlock_str64 : "+sBlock_str64);
var sBlock = CryptoJS.enc.Base64.parse(sBlock_str64);
        console.log(sBlock);`

I have an issue with crypto-js enc.Base64.parse()
In Node-Red : TypeError: base64Str.indexOf is not a function
In https://tonicdev.com/npm/crypto-js# : TypeError : undefined is not a function

Have you ever met such an error with enc-base64.js ?
Extract : 
`/**
             \* Converts a Base64 string to a word array.
             *
             \* @param {string} base64Str The Base64 string.
             *
             \* @return {WordArray} The word array.
             *
             \* @static
             *
             \* @example
             *
             \*     var wordArray = CryptoJS.enc.Base64.parse(base64String);
             */
            parse: function (base64Str) {
                // Shortcuts
                var base64StrLength = base64Str.length;
                var map = this._map;

```
            // Ignore padding
            var paddingChar = map.charAt(64);
            if (paddingChar) {
                var paddingIndex = base64Str.indexOf(paddingChar);
                if (paddingIndex != -1) {
                    base64StrLength = paddingIndex;
                }
            }

            // Convert
            var words = [];
            var nBytes = 0;
            for (var i = 0; i < base64StrLength; i++) {
                if (i % 4) {
                    var bits1 = map.indexOf(base64Str.charAt(i - 1)) << ((i % 4) * 2);
                    var bits2 = map.indexOf(base64Str.charAt(i)) >>> (6 - (i % 4) * 2);
                    var bitsCombined = bits1 | bits2;
                    words[nBytes >>> 2] |= (bitsCombined) << (24 - (nBytes % 4) * 8);
                    nBytes++;
                }
            }

            return WordArray.create(words, nBytes);
        },

        _map: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/='
    };`
```

Thanks in advance !

**Comment by ghost** [comment]
`CryptoJS.AES.encrypt` is taking `WordArray`s as arguments. Use `CryptoJS.lib.WordArray.create` to convert your `Array`|`UInt8Array` to it :-)
As far I remember, the result will be stored inside a `WordArray` too.

**Comment by VM999** [comment]
Thanks.
I have finally used : CryptoJS.enc.Hex.parse( ) which creates a WordArray (32bits Words) from a String.
