### ISSUE TITLE
Please enable private disclosures ASAP

### ISSUE THREAD

**Issue by Zemnmez** [brix/crypto-js#466]
You can do it with the [Security panel].

Please enable:

 * "Security advisories"
 * "Private vulnerability reporting"

I found a serious vulnerability in [crypto-js]. Please enable vulnerability disclosures so I can responsibly disclose the vulnerability. Thanks.

Twitter thread with some context: https://twitter.com/zemnmez/status/1714513369745830026

[Security panel]: https://github.com/Zemnmez/monorepo/security
[crypto-js]: https://github.com/brix/crypto-js

**Comment by wulinnan** [comment]
hello,I'd like to ask about this vulnerability, what exactly is it and is it easy to say, because I see that this library is supposed to be the most popular at the moment and have recently wanted to use it.

**Comment by MaksimKiselev** [comment]
@Zemnmez  https://twitter.com/evanvosberg

<img width="1061" alt="image" src="https://github.com/brix/crypto-js/assets/4495801/0b8e796e-4cfb-490c-b313-3168f64aa868">

<img width="345" alt="image" src="https://github.com/brix/crypto-js/assets/4495801/844ac660-2588-48e9-92d2-38caf6833231">


<img width="941" alt="image" src="https://github.com/brix/crypto-js/assets/4495801/771cb573-afbe-42bb-9405-891ed14b703e">

**Comment by Zemnmez** [comment]
@MaksimKiselev https://twitter.com/zemnmez/status/1714167497551925457

**Comment by Zemnmez** [comment]
> hello,I'd like to ask about this vulnerability, what exactly is it and is it easy to say, because I see that this library is supposed to be the most popular at the moment and have recently wanted to use it.

I can't answer this question without doing serious damage by disclosing it when there is no patch.

**Comment by evanvosberg** [comment]
@Zemnmez reporting vulnerabilities is enabled now, although the project itself is discontinued.

**Comment by Zemnmez** [comment]
https://github.com/brix/crypto-js/security/advisories/GHSA-xwcq-pm8m-c4vf

**Comment by Neustradamus** [comment]
@Zemnmez, @wulinnan, @MaksimKiselev, @evanvosberg: I have done an important announcement here:
- https://github.com/brix/crypto-js/issues/536

The solution is to replace by crypto-es:
- https://github.com/entronad/crypto-es
- https://github.com/entronad/crypto-es/tags
- https://github.com/entronad/crypto-es/releases
