### ISSUE TITLE
Security vulnerability in crypto-js@4.2.0

### ISSUE THREAD

**Issue by syukronarie** [brix/crypto-js#467]
Hi maintainers,

I am reporting a security vulnerability in crypto-js@4.2.0
Vulnerability type: Use of Weak Hash [High Severity]
Additional information: https://security.snyk.io/vuln/SNYK-JS-CRYPTOJS-6028119
<img width="838" alt="Screenshot 2023-10-25 at 9 14 54 AM" src="https://github.com/brix/crypto-js/assets/36725290/8add397a-5899-44d5-ba89-274f0e1e41af">

Best regards,
Arie

**Comment by evanvosberg** [comment]
This is wrong, the vulnerability effects all versions prior `4.2.0`

The vulnerability only effects usage of `PBKDF2` and only if you use it with the weak default configuration.
