### ISSUE TITLE
After upgrading from CryptoJS v4.0.0 to v4.2.0

### ISSUE THREAD

**Issue by deepakpm** [brix/crypto-js#473]
After upgrading from CryptoJS v4.0.0 to v4.2.0, we are encountering a UTF-8 malformed exception when attempting to decrypt text that was previously encrypted and stored using the v4.0.0 version of CryptoJS with AES encryption.

`
const decryptInto = (transitmessage, pass) => {
  try {
    var keySize = 256;
    var iterations = 100;
    let salt = Crypto.enc.Hex.parse(transitmessage.substr(0, 32));
    let iv = Crypto.enc.Hex.parse(transitmessage.substr(32, 32));
    let encrypted = transitmessage.substring(64);

    let key = Crypto.PBKDF2(pass, salt, {
      keySize: keySize / 32,
      iterations: iterations,
    });

    let decrypted = Crypto.AES.decrypt(encrypted.toString(), key, {
      iv: iv,
      padding: Crypto.pad.Pkcs7,
      mode: Crypto.mode.CBC,
    });
    return JSON.parse(decrypted.toString(Crypto.enc.Utf8));
`

`
 static encryptUsingPBKDF2Algorithm(msg, pass) {
    try {
      var salt = CryptoJS.lib.WordArray.random(128 / 8);

      var key = CryptoJS.PBKDF2(pass, salt, {
        keySize: keySize / 32,
        iterations: iterations,
      });

      var iv = CryptoJS.lib.WordArray.random(128 / 8);
      var value = JSON.stringify(msg);
      var encrypted = CryptoJS.AES.encrypt(value, key, {
        iv: iv,
        padding: CryptoJS.pad.Pkcs7,
        mode: CryptoJS.mode.CBC,
      });

      // salt, iv will be hex 32 in length
      // append them to the ciphertext for use  in decryption
      var transitmessage =
        salt.toString() + iv.toString() + encrypted.toString();
      return transitmessage;
    } catch (error) {
      return " ";
    }
  }
`

**Comment by deepakpm** [comment]
Resolved the issue added hasher 

const getKey = (transitmessage, pass, hasher) => {
  var salt = CryptoJS.enc.Hex.parse(transitmessage.substr(0, 32));
  var iv = CryptoJS.enc.Hex.parse(transitmessage.substr(32, 32));
  var key = CryptoJS.PBKDF2(pass, salt, {
    keySize: keySize / 32,
    iterations: iterations,
    hasher: hasher,
  });
  return {
    iv,
    key,
  };
};

**Comment by loxator** [comment]
This helped me with the issue, 4.2.0 has changed its default hasher, I had to specify to decrypt with SHA1 in my case as that's what it was encrypted with in another application.
