### ISSUE TITLE
CryptoJS.PBKDF2 v4.1.x v4.2.x return values are inconsistent

### ISSUE THREAD

**Issue by renfei** [brix/crypto-js#479]
Hi there,

use v4.1.1 ```https://cdnjs.cloudflare.com/ajax/libs/crypto-js/4.1.1/crypto-js.min.js``` 

```text
<<< CryptoJS.PBKDF2("1", "1", {keySize: 4}).toString()
>>> '68757d8c38f04fb9deb8ef65d62b6bce'
```

use v4.2.0 ```https://cdnjs.cloudflare.com/ajax/libs/crypto-js/4.2.0/crypto-js.min.js``` 

```text
<<< CryptoJS.PBKDF2("1", "1", {keySize: 4}).toString()
>>> '884c166a16838ca0fe1708138b690501'
```

Their return values are different, is it my problem?

Thank you all.

**Comment by kishieel** [comment]
The default configuration for pbkdf2 has been changed, leading to this behavior. If you need to maintain consistency with the previous version of your code, you may explicitly use the old configuration in your code. However, as @Zemnmez explained in his vulnerability report, this might not be the most secure solution.

References: 
https://github.com/brix/crypto-js/commit/421dd538b2d34e7c24a5b72cc64dc2b9167db40a
https://github.com/brix/crypto-js/security/advisories/GHSA-xwcq-pm8m-c4vf

**Comment by dlguswo333** [comment]
You might want to checkout this commit: https://github.com/brix/crypto-js/commit/421dd538b2d34e7c24a5b72cc64dc2b9167db40a

Check whether you are calling the function with same hasher and iterations.

**Comment by renfei** [comment]
Thanks for your answers
