### ISSUE TITLE
Error if used AES in AMD

### ISSUE THREAD

**Issue by wikin** [brix/crypto-js#49]
hello,
i tried to use AMD version and link just a  aes.js file and method "encrypt" returns with error
`cipher-core.js:775 Uncaught TypeError: Cannot read property 'create' of undefined`

example of my code:

``` javascript
define([
    'crypto-js/aes',
    'crypto-js/enc-utf8'
], function(
    AES,
    Utf8
) {
    var cipherText = AES.encrypt(text,passphrase).toString();
})
```

i found it can be fixed in file cipher-core.js by adding "./evpkdf" 

``` javascript
define(["./core", "./evpkdf"], factory);
```

**Comment by evanvosberg** [comment]
Thanks for reporting, will take a look for.

**Comment by evanvosberg** [comment]
Strange, because `evpkdf` is  a dependency of `aes` and should be available in this case.

**Comment by evanvosberg** [comment]
Fix by this [commit](https://github.com/brix/crypto-js/commit/7eff3bc9fb46cd5cb5717a9f0038c5f7612373c7), will be part of the next release.

**Comment by wikin** [comment]
;( not solving my problem
