### ISSUE TITLE
How to check the password is correct?

### ISSUE THREAD

**Issue by D0n9X1n** [brix/crypto-js#50]
Thanks for providing such a wonderful library.
Here is my situation, I have a function to decrypt aes content.

```
/**
 * decryptAES content
 * @param content 
 * @param pass the password
 * @return content or false when wrong password
 */
function decryptAES(content, pass) {
    var result = false;
    try {
        var bytes = CryptoJS.AES.decrypt(content, pass);
        var content = bytes.toString(CryptoJS.enc.Utf8);
        console.log(content);
        if (content != '') {
            result = content;
        }
    } catch (e) {}
    return result;
}
```

But, if the content is empty, the function return false, but the password is correct. So, is there a better way to check the password is correct? Thanks for any suggestions.

**Comment by zjx20** [comment]
@MikeCoder I have the same question. Could you please tell me how did you solve the problem? Thanks in advance!

I guess I need to design some kind of format for encrypting, so that after decrypting, I can verify if the decrypted value is valid.

**Comment by D0n9X1n** [comment]
@zjx20  I suggest you to use Base64 format to encode your content first. 
My case is to encrypt and decrypt content for the HTML page. So, I can add `<p></p>` to avoid the empty content case.

**Comment by zjx20** [comment]
Got it, thank you very much!
