### ISSUE TITLE
How to delete unuseful file ?

### ISSUE THREAD

**Issue by KrisCY** [brix/crypto-js#52]
hello , if i only want aes , can i delete other files? how?

**Comment by evanvosberg** [comment]
Common way is to use Crypto-JS with module loaders like `CommonJS` in `npm` or `AMD` with `RequireJS`. In those cases `require('crypto-js/aes')` only loads the required files for aes into your runtime. 

But in fact there are a lot of files aes depends on, so it's not recommended to delete any of the other files.
