### ISSUE TITLE
Relationship with sytelus/CryptoJS

### ISSUE THREAD

**Issue by ghost** [brix/crypto-js#53]
I was wondering what kind of relationship exists, if any, between this library and [sytelus/CryptoJS](https://github.com/sytelus/CryptoJS). Google shows your library and sytelus's as first ones, and it seems that both are based on [Jeff Mott's crypto-js](https://code.google.com/archive/p/crypto-js/). Would it be possible to merge the two libraries, so that features and updates do not make the two libraries diverge any further and there is one, robust library holding a full cryptographic suite?

Thanks,
Sam

**Comment by evanvosberg** [comment]
The library from [styleus/CryptoJS](https://github.com/sytelus/CryptoJS) has not been changing for years. and it's just a clone of the former SVN hosted project ported to git. 

The intention of creating this library was a different one, the idea was to make it working with the two most common module loader styles in JavaScript `CommonJS` and `AMD`. Additionally all the small junk files/modules of CryptoJS depend on each other. This project provides a way to load only those junks you need without loading modules double, it saves memory and makes it easier to access what you really need. 

One more thing, this library pulled some further fixes which where not included in the last SVN release (3.1.2) and even got some small contributions e.g. making random more random ...

So I think it makes no sense to merge, the other one never was under development after porting it to git.
