### ISSUE TITLE
Es6 how to correctly import SHA256 algo

### ISSUE THREAD

**Issue by kilianc** [brix/crypto-js#55]
given

``` js
import pbkdf2 from 'crypto-js/pbkdf2'
import crypto from 'crypto-js'

pbkdf2(password, salt, {
  iterations: 10,
  hasher: crypto.algo.SHA256,
  keySize: 256
})
```

how do I change this code to import only the SHA256 algo without carrying the whole library around in my bundle?

**Comment by evanvosberg** [comment]
Should work that way

```
import pbkdf2 from 'crypto-js/pbkdf2'
import SHA256 from 'crypto-js/sha256'

pbkdf2(password, salt, {
  iterations: 10,
  hasher: SHA256,
  keySize: 256
})
```

**Comment by kilianc** [comment]
I tried that but I get:

```
hmac.js:41Uncaught TypeError: hasher.init is not a constructor
```

**Comment by evanvosberg** [comment]
Sorry, you're right because it exports just the shortcut.

Did not test this, but give it a try. It should load the core plus the modules you need. All other modules depend on the core and extend it.

```
import crypto from 'crypto-js/core'
import pbkdf2 from 'crypto-js/pbkdf2'
import SHA256 from 'crypto-js/sha256'

pbkdf2(password, salt, {
  iterations: 10,
  hasher: crypto.algo.SHA256,
  keySize: 256
})
```

**Comment by kilianc** [comment]
Yeah I figured out looking at the source code. Still this is pretty awkward to since `SHA256` ends being an unused dependency

**Comment by nagiek** [comment]
This is still an issue today. Could be really helpful to export the algo directly from the SHA256 file.
