### ISSUE TITLE
Getting different values than that from original cryptoJS for Javascript

### ISSUE THREAD

**Issue by dylanh724** [brix/crypto-js#58]
I'm doing  this on my node server with crypto-js:

`var secret = CryptoJS.enc.Base64.stringify( CryptoJS.HmacSHA256(nonce, "my_secret_key") );`

and it's "working", but getting different values than doing the same on JS with the original CryptoJS (client side).

Anyone know what I can do to produce the same results? I originally moved it to node so that I could hide my secret key, but having trouble returning what the original code was expecting (different values)

**Comment by sebilasse** [comment]
By "original" do you mean https://code.google.com/archive/p/crypto-js/ ?
I noticed that too, the above is correct (according to a cross check with node.js crypto) …

**Comment by dylanh724** [comment]
> By "original" do you mean https://code.google.com/archive/p/crypto-js/ ?

@sebilasse : Yes, that is correct.

Hmm - you are also saying that you are producing different values when using my expression above?

Thanks~

**Comment by evanvosberg** [comment]
Can't reproduce this, just downloaded the "original" code [here](https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/crypto-js/CryptoJS%20v3.1.2.zip) and compared the results. Can't see any differents.

**Comment by evanvosberg** [comment]
Just one thing it might be different text encoding ... `UTF-8`, `Windows Latin 1`, `...` leading to different results.
