### ISSUE TITLE
Don't uglify NPM package source files

### ISSUE THREAD

**Issue by kyledrake** [brix/crypto-js#6]
The NPM source is uglified, which makes it difficult to debug errors when using it.

I think it's best to not uglify the package, and people interested in doing so for browser usage can then run it through browserify and uglify when needed.

This is related to https://github.com/bitcoinjs/bitcoinjs-lib/pull/57

**Comment by weilu** [comment]
:+1:

**Comment by ghost** [comment]
Unfortunately, I can't publish the changed package.

on `npm login` I get the following error:

```
npm http PUT https://registry.npmjs.org/-/user/org.couchdb.user:evanvosberg
npm http 503 https://registry.npmjs.org/-/user/org.couchdb.user:evanvosberg
npm ERR! registry error parsing json
```

Login on the npm web-page works but not in the terminal ... ((

**Comment by kyledrake** [comment]
Thank you for doing this! You are awesome.

There appear to be a downtime at the moment, but they should resolve it soon: https://twitter.com/npmjs/status/423185634581176320

Please let us know when you can push and we will quickly get this implemented. Thanks!

**Comment by kyledrake** [comment]
Err, hmm, that's an old tweet. The status seems to be working: http://status.npmjs.org/

Maybe try upgrading npm to the latest version?

**Comment by ghost** [comment]
Published!

**Comment by weilu** [comment]
:sparkles:

**Comment by kyledrake** [comment]
Thank you! :metal:

**Comment by Neustradamus** [comment]
Dear all: I have done an important announcement here:
- https://github.com/brix/crypto-js/issues/536

The solution is to replace by crypto-es:
- https://github.com/entronad/crypto-es
- https://github.com/entronad/crypto-es/tags
- https://github.com/entronad/crypto-es/releases
