### ISSUE TITLE
Encrypted string not printing in console

### ISSUE THREAD

**Issue by sanjsdev** [brix/crypto-js#74]
i tried below code 
var CryptoJS = require("crypto-js");
// Encrypt
var ciphertext = CryptoJS.AES.encrypt('my message', 'secret key 123');
console.log(ciphertext);

when i print the ciphertext variable in console its printing a big log instead of printing encrypted sting.
i tried like this with simple js file and its working. here is example. https://jsfiddle.net/cuhkppgx/4/
 any suggestions how do i get same in node file too.

Solution : got that by doing console.log(ciphertext.toString());

**Comment by brunocascio** [comment]
Try with this:


```
var encrypted = CryptoJS.AES.encrypt("my message", "Secret Passphrase");
//U2FsdGVkX18ZUVvShFSES21qHsQEqZXMxQ9zgHy+bu0=

var decrypted = CryptoJS.AES.decrypt(encrypted, "Secret Passphrase").toString(CryptoJS.enc.Utf8);
// my message


document.getElementById("demo1").innerHTML = encrypted;
document.getElementById("demo2").innerHTML = decrypted;
document.getElementById("demo3").innerHTML = decrypted;

```
