### ISSUE TITLE
cdn

### ISSUE THREAD

**Issue by mafar** [brix/crypto-js#75]
Is there cdn for this repo so it can be used with jsfiddle

**Comment by evanvosberg** [comment]
Might be available soon via cdnjs, see: https://github.com/cdnjs/cdnjs/issues/9958

**Comment by PeterDaveHello** [comment]
what are the files should be hosted? would you guys like to send a PR to cdnjs? thanks

**Comment by evanvosberg** [comment]
The master branch contains only release files, so those are the files to use for cdn.

**Comment by PeterDaveHello** [comment]
I still don't know what are the files we should host ... and we don't take "master" branch as a valid version.

**Comment by evanvosberg** [comment]
I just forked cdnjs, will create a pull request for ...

**Comment by PeterDaveHello** [comment]
thanks

**Comment by noway** [comment]
can be used with unpkg.com like this:
```
https://unpkg.com/crypto-js@3.1.9-1/sha256.js
```

**Comment by PeterDaveHello** [comment]
@evanvosberg any help do you need? Or you can just tell me what are the files need to be hosted :smile:

**Comment by evanvosberg** [comment]
@noway421 thanks for that great tip. Didn't know this yet.

@PeterDaveHello still want to do the PR, but the repo is that much big that I'm currently running out of disk space. Next week will get a new device with more space, then I'll continue ...

**Comment by PeterDaveHello** [comment]
@evanvosberg If you'll like to work locally, I'll suggest you start with sparseCheckout: https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md, since there are too many files in this repo, without sparseCheckout, the whole process will be super slow, and take 77 GB disk space, with sparseCheckout, it'll need only 3GB.

**Comment by PeterDaveHello** [comment]
Here are the docs about how to add a library:

 - https://github.com/cdnjs/cdnjs#adding-a-new-or-updating-an-existing-library
 - https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md#d-adding-a-new-library

**Comment by evanvosberg** [comment]
@PeterDaveHello as the pr is finally merged when will it be available [here](https://cdnjs.com/libraries/crypto-js/) ?

**Comment by PeterDaveHello** [comment]
@evanvosberg just about 10 mins.

**Comment by PeterDaveHello** [comment]
@evanvosberg it's already online.

**Comment by evanvosberg** [comment]
great

**Comment by Neustradamus** [comment]
Dear all: I have done an important announcement here:
- https://github.com/brix/crypto-js/issues/536

The solution is to replace by crypto-es:
- https://github.com/entronad/crypto-es
- https://github.com/entronad/crypto-es/tags
- https://github.com/entronad/crypto-es/releases
