### ISSUE TITLE
Rollup files

### ISSUE THREAD

**Issue by NuclearPhoenixx** [brix/crypto-js#77]
Hi,

I know that this is not the proper place to post this but I don't know where else to ask.
Firstly, I'm a newbie to this, so sorry for everything.

Secondly, how can I create a rollup file so that I don't have to worry about dependencies and have everything in one file combined?

Thanks in advance!

**Comment by evanvosberg** [comment]
Just select a release version e.g. the latest [3.1.9](https://github.com/brix/crypto-js/tree/3.1.9) and select the [crypto-js.js](
https://github.com/brix/crypto-js/blob/3.1.9/crypto-js.js) file.

**Comment by NuclearPhoenixx** [comment]
Thanks! 👍
