### ISSUE TITLE
cannot install via npm

### ISSUE THREAD

**Issue by netfurk** [brix/crypto-js#8]
error parsing json SyntaxError: Unexpected token s 
Node.js v0.10.26 npm windows

**Comment by ghost** [comment]
Does the issue still exists? 
Is there somebody else who can reproduce it?

Unfortunately I don have a Windows machine at all ...

**Comment by toymachiner62** [comment]
I'm on a windows machine and I did `$ npm install crypto-js` and it worked just fine for me. I'm also on version 0.10.26.
