### ISSUE TITLE
SHA256 hash of a file generated does not match with SHA256 from other sites

### ISSUE THREAD

**Issue by thackerronak** [brix/crypto-js#89]
```
var SHA256 = require("crypto-js/sha256");
 onFilesChange(fileList : Array<File>){
        this.fileList = fileList;
        console.log(fileList);
        for(var file in fileList){
          this.hash = SHA256(file);
          console.log(this.hash.toString());
}
    
```
File : [file for sha-256][1]
with above code I got below sh256 hash : 5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91b46729d73a27fb57e9

but I refer many online sites like http://onlinemd5.com/,http://www.online-convert.com/,https://md5file.com/calculator

form online site I got below sha256 hash :
27bb4358e847d559bed9f34eeee51ca71f51542afb0de4017b80dd66a0656eca

can anyone tell me why I'm getting different hash?

  [1]: https://file.io/uWoIvh

**Comment by poluxus** [comment]
For me it is `\n` that differ the hash

**Comment by evanvosberg** [comment]
Is related to this issue: https://github.com/brix/crypto-js/issues/92

**Comment by poluxus** [comment]
Sorry i didn't come back on this.
I've been able to get it work even if i dont get the same hash on my end...
Thanks for your work
