### ISSUE TITLE
please add bower.json

### ISSUE THREAD

**Issue by stasberkov** [brix/crypto-js#9]
please add bower.json to make package installable via bower package manager

**Comment by ghost** [comment]
This repository is a **modularized** port of googlecode project crypto-js.

By adding a bower.json to the repository, it would be possible to load the repo with the bower package manager. But it would not be possible to load single modules.

Example:

**bower.json:**

``` json
{
  "name": "crypto-js",
  "version": "0.0.0",
  "main": "build/bower/crypto-js.js"
}
```

**Load the full Library:**

``` js
var CryptoJS = require("crypto-js");

// Resolved path -> works
"*/bower_components/crypto-js/build/bower/crypto-js.js";
```

``` js
// Load the full Library
var AES = require("crypto-js/aes");

// Resolved path -> fails
"*/bower_components/crypto-js/aes.js";

// Location of the module
"*/bower_components/crypto-js/build/bower/aes.js";
```

Actually `repository !== package`, but for bower it's the same. I didn't find a solution to set a package root directory inside of the repository for bower.

**Comment by calebmadrigal** [comment]
+1

**Comment by kirill-konshin** [comment]
It would be possible to load only certain modules if you'll configure requirejs like that:

``` js
require.config({
    packages: [
        {
            name: 'crypto-js',
            location: 'path-to/bower_components/crypto-js',
            main: 'index'
        }
    ]
});
```

require('crypto-js/aes') will load only AES.

**Comment by kirill-konshin** [comment]
Created pull request https://github.com/evanvosberg/crypto-js/pull/20

**Comment by kirill-konshin** [comment]
Previous PR was closed and new PR https://github.com/evanvosberg/crypto-js/pull/21 for `develop` branch has been created.

**Comment by evanvosberg** [comment]
It's in now.

**Comment by Neustradamus** [comment]
Dear all: I have done an important announcement here:
- https://github.com/brix/crypto-js/issues/536

The solution is to replace by crypto-es:
- https://github.com/entronad/crypto-es
- https://github.com/entronad/crypto-es/tags
- https://github.com/entronad/crypto-es/releases
